const { shilohUiPrimitiveStyles } = require('./shilohUiPrimitives');

function escapeHtml(value = '') { return String(value).replace(/[&<>"']/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[char]); }
function baseStyles() { return `${shilohUiPrimitiveStyles()}:root{--ink:#20322b;--muted:#56685f;--panel:#fffdf9;--line:#dce3dd;--line-strong:#c8d3cb;--leaf-soft:#e7eee9;--leaf-deep:#294c3c}*{box-sizing:border-box}body{font-family:Inter,system-ui,-apple-system,sans-serif}.eyebrow{font-size:.68rem;text-transform:uppercase;letter-spacing:.1em;font-weight:850;color:var(--muted)}h2{font-size:1.05rem;margin:0 0 12px}h3{font-size:.9rem;margin:0}.back{display:inline-flex;align-items:center;min-height:44px}`; }

function rand(value) { return new Intl.NumberFormat('en-ZA', { style:'currency', currency:'ZAR' }).format(Number(value || 0)); }

function renderCalendarPaymentPage({ model, csrfToken = '', clientScriptPath = '/calendar/payments/client.js' } = {}) {
  const { subject, payment, authority } = model;
  const status = payment.state === 'overpaid' ? 'Overpayment needs attention' : payment.state === 'paid' ? 'Paid in full' : payment.state === 'partially_paid' ? 'Partially paid' : payment.state === 'partially_refunded' ? 'Refunded in part' : 'Unpaid';
  const requests = payment.requests.map(item => `<li><span><strong>${escapeHtml(rand(item.amount))} · Ozow</strong><small>${escapeHtml(item.state.replaceAll('_',' '))}</small></span>${item.provider_payment_url ? `<button type="button" data-copy-link="${escapeHtml(item.provider_payment_url)}">Copy link</button>` : ''}</li>`).join('');
  const entries = payment.entries.map(item => `<li><span><strong>${item.entry_type === 'refund' ? 'Refund' : 'Payment'} · ${escapeHtml(item.method.replaceAll('_',' '))}</strong><small>${escapeHtml(new Date(item.created_at).toLocaleString('en-ZA'))}</small></span><b>${item.entry_type === 'refund' ? '−' : '+'}${escapeHtml(rand(item.amount))}</b></li>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Booking payment · Shiloh</title><style>${baseStyles()}
body{background:#f5f3ed;color:var(--ink);margin:0}.payment-shell{width:min(860px,100%);margin:auto;padding:24px}.payment-head{display:flex;align-items:start;justify-content:space-between;gap:14px}.payment-head h1{margin:3px 0;font-size:1.6rem}.back{color:var(--leaf-deep);font-weight:800}.payment-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:16px;margin-top:18px}.payment-card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:18px}.balance{background:var(--leaf-soft);display:grid;grid-template-columns:repeat(3,1fr);gap:8px;border-radius:12px;padding:14px}.balance span{display:grid;gap:3px}.balance small,.hint,li small{color:var(--muted)}.balance strong{font-size:1.15rem}.state{display:inline-flex;border-radius:999px;padding:5px 9px;background:#e7eee9;font-weight:850}.forms{display:grid;gap:16px}.payment-form{display:grid;gap:9px;border-top:1px solid var(--line);padding-top:15px}.payment-form:first-child{border:0;padding-top:0}.payment-form label{display:grid;gap:5px;font-size:.78rem;font-weight:800}.payment-form input,.payment-form select{min-height:44px;border:1px solid var(--line-strong);border-radius:9px;padding:9px;font:inherit}.payment-form button,li button{min-height:44px;border:0;border-radius:9px;background:var(--leaf-deep);color:#fff;padding:9px 13px;font:inherit;font-weight:850}.payment-list{list-style:none;padding:0;margin:10px 0;display:grid;gap:8px}.payment-list li{display:flex;justify-content:space-between;align-items:center;gap:10px;border:1px solid var(--line);border-radius:10px;padding:10px}.payment-list span{display:grid;gap:3px}.status{min-height:22px;margin:8px 0;color:var(--leaf-deep);font-weight:750}@media(max-width:700px){.payment-shell{padding:14px}.payment-grid{grid-template-columns:1fr}.payment-head{display:grid}.balance{grid-template-columns:1fr}.payment-card{padding:14px}.payment-form input,.payment-form select,.payment-form button,li button{font-size:16px;min-height:44px}}</style></head><body>
<main class="payment-shell" data-payment-page data-appointment-id="${subject.appointmentId}" data-csrf="${escapeHtml(csrfToken)}"><header class="payment-head"><div><span class="eyebrow">Booking payment</span><h1>${subject.groupId ? `Linked booking #${subject.groupId}` : `Appointment #${subject.appointmentId}`}</h1><span class="state">${escapeHtml(status)}</span></div><a class="back" href="/calendar/read-only?appointment=${subject.appointmentId}">Back to appointment</a></header><p class="status" role="status" data-payment-status></p>
<section class="payment-card"><div class="balance"><span><small>Booking total</small><strong>${escapeHtml(rand(payment.amountDue))}</strong></span><span><small>Net received</small><strong>${escapeHtml(rand(payment.netPaid))}</strong></span><span><small>Outstanding</small><strong>${escapeHtml(rand(payment.outstanding))}</strong></span></div><p class="hint">One person can pay the full balance, or you can create separate requests for a couple or group. Payment never changes attendance or booking status.</p></section>
<div class="payment-grid"><section class="payment-card forms"><h2>Collect payment</h2>${authority.canCollect ? `<form class="payment-form" data-ozow-form><h3>Ozow payment link</h3><label>Amount (R)<input name="amount" inputmode="decimal" value="${escapeHtml(payment.outstanding)}" required></label><label>Payer name <input name="payerName"></label><label>Payer mobile <input name="payerMobile" inputmode="tel"></label><button ${authority.ozowConfigured ? '' : 'disabled'}>Create secure payment link</button>${authority.ozowConfigured ? '' : '<small>Ozow will become available after its merchant credentials are configured.</small>'}</form><form class="payment-form" data-manual-form><h3>Record payment received</h3><label>Amount (R)<input name="amount" inputmode="decimal" value="${escapeHtml(payment.outstanding)}" required></label><label>Method<select name="method"><option value="card_machine">Card machine</option><option value="cash">Cash</option><option value="manual_eft">EFT</option></select></label><label>Notes (optional)<input name="notes" maxlength="240"></label><button>Record payment</button></form>` : '<p>You can view this payment, but cannot collect it.</p>'}</section>
<section><div class="payment-card"><h2>Payment requests</h2><ul class="payment-list" data-payment-requests>${requests || '<li>No payment links yet.</li>'}</ul></div><div class="payment-card" style="margin-top:16px"><h2>History</h2><ul class="payment-list">${entries || '<li>No payments recorded yet.</li>'}</ul></div></section></div></main><script src="${escapeHtml(clientScriptPath)}" defer></script></body></html>`;
}

function calendarPaymentsClientScript() {
  return `(()=>{'use strict';const root=document.querySelector('[data-payment-page]');if(!root)return;const id=root.dataset.appointmentId,status=root.querySelector('[data-payment-status]');const operation=()=>crypto.randomUUID().replaceAll('-','');async function post(path,body){const response=await fetch('/calendar/payments/appointments/'+id+'/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Shiloh-CSRF-Token':root.dataset.csrf},body:JSON.stringify({...body,operationId:operation()})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Payment operation failed.');return data;}document.addEventListener('click',async event=>{const button=event.target.closest('[data-copy-link]');if(!button)return;await navigator.clipboard.writeText(button.dataset.copyLink);status.textContent='Payment link copied.';});const manual=root.querySelector('[data-manual-form]');if(manual)manual.addEventListener('submit',async event=>{event.preventDefault();status.textContent='Recording payment…';try{const data=await post('manual',Object.fromEntries(new FormData(manual)));status.textContent=data.status==='recorded'?'Payment recorded. Refreshing…':'Payment was already recorded.';location.reload();}catch(error){status.textContent=error.message;}});const ozow=root.querySelector('[data-ozow-form]');if(ozow)ozow.addEventListener('submit',async event=>{event.preventDefault();status.textContent='Creating secure link…';try{const data=await post('ozow',Object.fromEntries(new FormData(ozow)));await navigator.clipboard.writeText(data.request.provider_payment_url);status.textContent='Secure payment link created and copied.';location.reload();}catch(error){status.textContent=error.message;}});})();`;
}

function calendarPaymentLinkClientScript() {
  return `(()=>{'use strict';
function idFromCard(card){const raw=String(card&&card.dataset&&(card.dataset.eventId||card.dataset.appointmentId)||'');const match=raw.match(/(?:appointment-)?(\\d+)/);return match?match[1]:'';}
function idFromDialog(dialog){const title=dialog&&dialog.querySelector('[data-details-title]');const match=String(title&&title.textContent||'').match(/#(\\d+)/);return match?match[1]:'';}
function cardForId(id){return Array.from(document.querySelectorAll('.event-card[data-kind="appointment"][data-canonical="true"]')).find(card=>idFromCard(card)===String(id));}
function addPaymentLink(card){const dialog=document.querySelector('[data-appointment-details-dialog]');if(!dialog||!dialog.open||dialog.querySelector('[data-details-payment]'))return;const id=idFromCard(card)||idFromDialog(dialog);if(!id)return;const link=document.createElement('a');link.dataset.detailsPayment='true';link.href='/calendar/payments/appointments/'+id;link.textContent='Payments';link.style.cssText='display:inline-flex;align-items:center;justify-content:center;min-height:44px;border:1px solid var(--leaf-deep,#294b3e);border-radius:9px;padding:10px 13px;color:var(--leaf-deep,#294b3e);font-weight:800;text-decoration:none';const actions=dialog.querySelector('.appointment-details-actions');if(actions)actions.insertBefore(link,actions.firstChild);}
function queue(card){window.setTimeout(()=>addPaymentLink(card||cardForId(idFromDialog(document.querySelector('[data-appointment-details-dialog]')))),0);}
window.addEventListener('click',event=>{const card=event.target.closest&&event.target.closest('.event-card[data-kind="appointment"][data-canonical="true"]');if(card)queue(card);},true);
queue();
})();`;
}

module.exports = { renderCalendarPaymentPage, calendarPaymentsClientScript, calendarPaymentLinkClientScript };
