'use strict';
const { workspaceShellStyles, renderWorkspaceNavigation, escapeHtml: esc } = require('./workspaceShell');
const { confirmationClientScript } = require('./workspaceConfirmation');
const rand = value => new Intl.NumberFormat('en-ZA', { style: 'currency', currency: 'ZAR' }).format(Number(value || 0));
const typeLabel = value => value === 'service_exchange' ? 'Service exchange' : 'Goodwill';
function renderTreatmentCreditPage({ model, csrfToken = '', clientScriptPath = '/calendar/treatment-credit/client.js' } = {}) {
  const { client, balance, entries, appointments, authority } = model;
  const history = entries.map(entry => `<li><div><strong>${entry.entry_type === 'issue' ? typeLabel(entry.credit_type) : 'Applied to treatment'}</strong><span>${esc(rand(entry.signed_amount))}</span></div><p>${esc(entry.reason)}${entry.reference ? ` · Reference: ${esc(entry.reference)}` : ''}</p><small>${esc(new Date(entry.created_at).toLocaleString('en-ZA', { timeZone: 'Africa/Johannesburg' }))} · ${esc(entry.actor_name)} · Entry #${esc(entry.id)}${entry.appointment_id ? ` · <a href="/calendar/payments/appointments/${esc(entry.appointment_id)}">Appointment #${esc(entry.appointment_id)}</a>` : ''}</small></li>`).join('');
  const issue = authority.canIssue ? `<section class="credit-card"><h2>Add treatment credit</h2><form data-credit-form="issue"><label>Type<select name="creditType"><option value="goodwill">Goodwill</option><option value="service_exchange">Service exchange</option></select></label><label>Amount (R)<input name="amount" type="number" min="0.01" max="9999999999.99" step="0.01" required></label><label class="credit-wide">Reason<input name="reason" maxlength="240" required></label><label class="credit-wide">Reference / supplier invoice<input name="reference" maxlength="120" aria-describedby="credit-reference-help"></label><p id="credit-reference-help" class="credit-wide credit-hint">For service exchange, keep the supplier invoice reference here. This records noncash credit; it does not record an invoice payment.</p><button class="credit-wide" data-workspace-action="primary">Add credit</button><p class="credit-wide credit-status" role="status" aria-live="polite"></p></form></section>` : '';
  const apply = authority.canApply && balance > 0 ? `<section class="credit-card"><h2>Apply to a treatment balance</h2><p>For completed treatment only. Deposits still need payment. Linked treatments must all be completed for this same client.</p>${appointments.length ? `<form data-credit-form="apply"><label class="credit-wide">Completed treatment<select name="appointmentId" required>${appointments.map(a => `<option value="${esc(a.id)}">#${esc(a.id)} · ${esc(a.title || 'Treatment')} · ${esc(new Date(a.starts_at).toLocaleDateString('en-ZA', { timeZone: 'Africa/Johannesburg' }))}</option>`).join('')}</select></label><label class="credit-wide">Amount (R)<input name="amount" type="number" min="0.01" max="${esc(balance)}" step="0.01" required></label><button class="credit-wide" data-workspace-action="primary">Apply credit</button><p class="credit-wide credit-status" role="status" aria-live="polite"></p></form>` : '<p>No completed treatments available.</p>'}</section>` : '';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Treatment credit — Shiloh Workspace</title><style>${workspaceShellStyles()}
    :root{--ink:#20322b;--muted:#56685f;--line:#dce3dd;--leaf-deep:#294c3c}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:#f6f4ef;font-family:Inter,system-ui,sans-serif}.credit-shell{max-width:1000px;margin:auto;padding:24px}.credit-back{display:inline-flex;align-items:center;min-height:44px;color:var(--leaf-deep)}h1{margin:12px 0 6px;font-size:1.7rem}h2{font-size:1.15rem;margin:0 0 14px}p{line-height:1.5}.credit-summary{padding:20px;border:1px solid #c8d3cb;border-radius:16px;background:#e7eee9;margin:20px 0}.credit-summary strong{display:block;font-size:2rem;color:var(--leaf-deep);margin-top:5px}.credit-columns{display:grid;grid-template-columns:1fr 1fr;gap:16px;align-items:start}.credit-card{min-width:0;padding:20px;background:#fffdf9;border:1px solid var(--line);border-radius:16px}.credit-card form{display:grid;grid-template-columns:1fr 1fr;gap:14px}.credit-card label{display:grid;gap:6px;font-weight:700}.credit-card input,.credit-card select{width:100%;min-width:0;min-height:46px;border:1px solid #a5b4aa;border-radius:9px;padding:10px;color:var(--ink);background:white;font:inherit}.credit-card button{min-height:46px;padding:12px;border-radius:10px;font:inherit;font-weight:750;cursor:pointer}.credit-wide{grid-column:1/-1}.credit-hint,.credit-card small{color:var(--muted);font-size:.85rem}.credit-hint{margin:0}.credit-history{margin:18px 0}.credit-history ul{list-style:none;padding:0;margin:0}.credit-history li{padding:16px 0;border-bottom:1px solid var(--line);overflow-wrap:anywhere}.credit-history li:last-child{border:0}.credit-history li>div{display:flex;justify-content:space-between;gap:12px}.credit-history p{margin:6px 0}.credit-history a{display:inline-flex;align-items:center;min-height:44px;color:var(--leaf-deep)}.credit-status:empty{display:none}.credit-status{margin:0}.credit-shell :focus-visible{outline:3px solid #294c3c;outline-offset:3px}@media(max-width:700px){.credit-shell{padding:64px 14px 18px}.credit-columns{grid-template-columns:1fr}.credit-card{padding:16px}.credit-card form{grid-template-columns:1fr}.credit-summary strong{font-size:1.75rem}}
  </style><script src="${esc(clientScriptPath)}" defer></script></head><body><div class="workspace-frame">${renderWorkspaceNavigation({ active: 'clients', dashboardHref: '/calendar/workspace', calendarHref: '/calendar/read-only', clientsHref: '/calendar/clients' })}<main class="workspace-main"><div class="credit-shell" data-treatment-credit data-client-id="${esc(client.id)}" data-csrf="${esc(csrfToken)}"><a class="credit-back" href="/calendar/clients/${esc(client.id)}">Back to client</a><h1>Treatment credit</h1><p>${esc(client.name)}</p><section class="credit-summary" aria-label="Remaining treatment credit"><span>Remaining treatment credit</span><strong>${esc(rand(balance))}</strong><p>Noncash credit for treatments. Separate from Rewards, gifts and money received.</p></section><div class="credit-columns">${issue}${apply}</div><section class="credit-card credit-history"><h2>Credit history</h2><ul>${history || '<li>No treatment credit recorded yet.</li>'}</ul></section></div></main></div></body></html>`;
}
function treatmentCreditClientScript() {
  return confirmationClientScript() + `(()=>{'use strict';const root=document.querySelector('[data-treatment-credit]');if(!root)return;root.querySelectorAll('[data-credit-form]').forEach(form=>{const storageKey='shiloh-treatment-credit:'+root.dataset.clientId+':'+form.dataset.creditForm;let pending=null,busy=false;try{pending=JSON.parse(sessionStorage.getItem(storageKey)||'null');}catch(_){sessionStorage.removeItem(storageKey);}const status=form.querySelector('[role="status"]'),button=form.querySelector('button');const type=form.elements.creditType,reference=form.elements.reference;if(pending&&pending.body){for(const [key,value] of Object.entries(pending.body)){if(form.elements[key])form.elements[key].value=value;}if(type)reference.required=type.value==='service_exchange';}if(type)type.addEventListener('change',()=>{reference.required=type.value==='service_exchange';});form.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;busy=true;button.disabled=true;try{const values={...Object.fromEntries(new FormData(form)),clientId:root.dataset.clientId};const signature=JSON.stringify(values);if(pending&&pending.signature!==signature)throw new Error('An earlier request needs review. Refresh and check the history before changing it.');if(!pending){if(!(await window.ShilohConfirm({title:form.dataset.creditForm==='issue'?'Add treatment credit?':'Apply treatment credit?',copy:'Record '+new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(Number(values.amount))+' as noncash treatment credit for this client.',cancel:'Go back',action:'Confirm credit',danger:false})))return;pending={signature,body:{...values,operationId:crypto.randomUUID()}};sessionStorage.setItem(storageKey,JSON.stringify(pending));}status.textContent='Saving credit…';const response=await fetch('/calendar/treatment-credit/'+form.dataset.creditForm,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Shiloh-CSRF-Token':root.dataset.csrf},body:JSON.stringify(pending.body)});const data=await response.json();if(!response.ok){if(response.status<500){pending=null;sessionStorage.removeItem(storageKey);}throw new Error(data.error||'Credit could not be saved.');}sessionStorage.removeItem(storageKey);status.textContent='Credit saved. Refreshing…';location.reload();}catch(error){status.textContent=error.message+(pending?' Retry this unchanged request, or check the history before adding another credit.':'');}finally{busy=false;button.disabled=false;}});});})();`;
}
module.exports = { renderTreatmentCreditPage, treatmentCreditClientScript };
