'use strict';

function escape(value) { return String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;'); }
const styles = `:root{font-family:Inter,system-ui,sans-serif;color:#253c32;background:#f6f3eb}*{box-sizing:border-box}body{margin:0}.wrap{max-width:760px;margin:auto;padding:clamp(20px,5vw,58px)}.brand{display:flex;align-items:center;gap:12px;font-size:16px;font-weight:700;margin-bottom:36px}.mark{border:1px solid #43614e;border-radius:50%;width:48px;height:48px;display:grid;place-items:center;font:italic 32px Georgia,serif}.card{background:#fffdf8;border:1px solid #d8e2d8;border-radius:26px;padding:clamp(24px,5vw,50px);box-shadow:0 16px 45px #344b3515}.eyebrow{text-transform:uppercase;letter-spacing:.16em;font-size:12px;color:#627765;font-weight:800}h1{font:normal clamp(30px,5vw,46px)/1.12 Georgia,serif;margin:12px 0 14px}p{line-height:1.6;color:#506159}.field{margin:20px 0}label{display:block;font-weight:700;margin-bottom:8px}input{width:100%;min-height:56px;border:1px solid #9dac9e;border-radius:12px;padding:12px 14px;font:inherit;font-size:18px}input:focus-visible,button:focus-visible,a:focus-visible{outline:3px solid #3b654c;outline-offset:3px}.button{display:inline-flex;align-items:center;justify-content:center;min-height:56px;min-width:180px;padding:12px 22px;border:0;border-radius:12px;background:#31533e;color:white;font:700 17px Inter,system-ui,sans-serif;cursor:pointer;text-decoration:none}.secondary{background:#ecf1ea;color:#31533e}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:26px}.error{background:#faece9;border-radius:10px;padding:12px;color:#873f36}.privacy{font-size:13px;margin-top:25px}@media(max-width:520px){.actions>*{width:100%}}`;
function shell(body) { return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Shiloh · Client check-in</title><style>${styles}</style></head><body><main class="wrap"><div class="brand"><img src="/assets/brand/shiloh-mark-192.png" alt="" width="48" height="48"><span>Shiloh Massage Therapy &amp; Aesthetic Clinic</span></div><section class="card">${body}</section></main></body></html>`; }
function welcome({ setup = false } = {}) { return shell(`<span class="eyebrow">Welcome to Shiloh</span><h1>${setup ? 'Please ask reception to set up this iPad.' : 'Let’s get you checked in.'}</h1><p>${setup ? 'A team member will help you get started.' : 'You can enter your details here, even if you have never used My Shiloh before.'}</p>${setup ? '' : '<form action="/check-in/start" method="post"><button class="button" type="submit">Start check-in</button></form>'}`); }
function details({ error = '', values = {} } = {}) { return shell(`<span class="eyebrow">Your details</span><h1>Tell us a little about yourself.</h1><p>These details help reception find the right client record. Your mobile number will be confirmed on your own phone later.</p>${error ? `<p class="error" role="alert">${escape(error)}</p>` : ''}<form method="post" action="/check-in/details" autocomplete="off"><div class="field"><label for="name">Full name</label><input id="name" name="name" autocomplete="name" maxlength="120" required value="${escape(values.name)}"></div><div class="field"><label for="mobile">Mobile number</label><input id="mobile" name="mobile" type="tel" inputmode="tel" autocomplete="tel" maxlength="24" required value="${escape(values.mobile)}"></div><div class="field"><label for="dateOfBirth">Date of birth</label><input id="dateOfBirth" name="dateOfBirth" type="date" autocomplete="bday" required value="${escape(values.dateOfBirth)}"></div><div class="actions"><button class="button" type="submit">Continue</button></div></form><form method="post" action="/check-in/finish"><button class="button secondary" type="submit">Cancel check-in</button></form><p class="privacy">Only Shiloh’s authorised team can review your details. Please hand the iPad back to reception when you’re done.</p>`); }
function done({ needsStaff = false } = {}) { return shell(`<span class="eyebrow">Thank you</span><h1>${needsStaff ? 'Reception will help with the next step.' : 'Your details are saved.'}</h1><p>Please hand the iPad back to reception. They will help you with any forms needed for your treatment.</p><a class="button" href="/check-in/">Finish</a>`); }
function setup() { return shell('<span class="eyebrow">Staff setup</span><h1>Activate client check-in</h1><p>Use this only on the clinic iPad. Activating check-in signs this device out of Workspace before you give it to a client.</p><button class="button" type="button" data-activate>Activate iPad</button><p role="status" data-status></p><script src="/calendar/check-in/setup.js" defer></script>'); }
function devices(items = []) { const rows = items.map(item => `<li><strong>iPad ${escape(item.id)}</strong> · ${escape(new Date(item.created_at).toLocaleDateString('en-ZA',{timeZone:'Africa/Johannesburg'}))} · ${item.revoked_at ? 'Disabled' : `<button class="button secondary" type="button" data-revoke="${escape(item.id)}">Disable iPad</button>`}</li>`).join(''); return shell(`<span class="eyebrow">Staff devices</span><h1>Clinic check-in iPads</h1><p>Disable a lost or retired iPad here. This ends access to check-in immediately.</p><ul>${rows || '<li>No iPads have been activated.</li>'}</ul><p role="status" data-status></p><script src="/calendar/check-in/devices.js" defer></script>`); }
module.exports = { shell, welcome, details, done, setup, devices };
