'use strict';
const { renderMyShilohBookingPage } = require('./myShilohBooking');
const { escapeHtml, webPolicyHtml } = require('./paymentPolicyUx');

function renderMyShilohCouplesBookingPage(options = {}) {
  const treatments = (options.catalogue || []).map(item => `<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)} · ${escapeHtml(item.duration)} · ${escapeHtml(item.price)}</option>`).join('');
  const guests = [0,1].map(index => `<fieldset class="date-card"><legend>${index ? 'Your guest' : 'You'}</legend><label for="couples-service-${index}">Treatment</label><select id="couples-service-${index}" data-couples-service="${index}"><option value="">Choose a treatment</option>${treatments}</select><label for="couples-staff-${index}">Therapist</label><select id="couples-staff-${index}" data-couples-staff="${index}" disabled><option value="">Choose a treatment first</option></select><p class="status" data-couples-practitioner-status="${index}" role="status"></p></fieldset>`).join('');
  const main = `<main class="shell" data-my-shiloh-couples data-csrf="${escapeHtml(options.csrfToken)}">
    <section class="intro"><div class="eyebrow">My Shiloh · Couples booking</div><h1>Book for two.</h1><p>Choose a treatment and therapist for each of you, then find a time when both therapists are available. One combined deposit is due after both appointments are approved.</p></section>
    <section class="step" data-couples-step="1"><div class="step-head"><h2>Who is joining you?</h2><p>You are booking for yourself, ${escapeHtml(options.clientFirstName)}, and one guest.</p></div><form data-couples-guest-form class="date-card">
      <label for="couples-guest-name">Guest’s first name and surname<input id="couples-guest-name" name="name" autocomplete="off" maxlength="120" required></label>
      <label for="couples-guest-mobile">Guest’s mobile number<input id="couples-guest-mobile" name="mobile" type="tel" inputmode="tel" autocomplete="off" maxlength="20" placeholder="082 123 4567" required></label>
      <p>Use your guest’s own South African mobile number. These details are for this booking; they do not sign your guest in or subscribe them to marketing.</p>
      <label class="confirm-label"><input name="consent" type="checkbox" required><span>My guest agrees to this booking and to sharing their name and mobile number with Shiloh.</span></label>
      <p class="status" data-couples-guest-status role="status"></p><div class="actions"><button class="button button--primary" type="submit">Choose our treatments</button><a class="button button--soft" href="/my-shiloh/book">Book for myself</a></div>
    </form></section>
    <section class="step" data-couples-step="2" hidden><div class="step-head"><h2>Choose for each person.</h2><p>Choose the same or different treatments, with a different therapist for each person.</p></div><div class="options">${guests}</div><p class="status" data-couples-selection-status role="status"></p><div class="actions"><button class="button button--primary" type="button" data-couples-next>Find a shared time</button><button class="button button--soft" type="button" data-couples-back="1">← Guest details</button></div></section>
    <section class="step" data-couples-step="3" hidden><div class="step-head"><h2>Find a time for both of you.</h2><p>Both treatments start together. Each therapist is checked for the full duration of their treatment.</p></div><div class="date-card"><label>Preferred date<input type="date" data-couples-date></label><div class="actions"><button class="button button--primary" type="button" data-couples-find>Show shared times</button></div></div><p class="status" data-couples-slot-status role="status"></p><div class="slots" data-couples-slots></div><div class="actions"><button class="button button--soft" type="button" data-couples-back="2">← Treatments and therapists</button></div></section>
    <section class="step" data-couples-step="4" hidden><div class="step-head"><h2>Review your booking for two.</h2><p>Check both appointments before sending your request.</p></div><div class="review-card"><p class="status" data-couples-review-status role="status" aria-live="polite"></p><div data-couples-review-items></div><div class="review-grid"><div><small>Total treatment value</small><strong data-couples-total>Checking…</strong></div><div><small>One combined deposit after both approvals</small><strong data-couples-deposit>Checking…</strong></div></div>
      <div class="actions"><button class="button button--soft" type="button" data-couples-retry hidden>Check our appointments again</button><button class="button button--soft" type="button" data-couples-back="3">← Change time</button><button class="button button--soft" type="button" data-couples-back="2">← Change treatments</button></div>
      <fieldset class="occasion-note"><legend>Is this booking for a special occasion?</legend><label><input type="radio" name="couples-occasion" value="no"> No</label><label><input type="radio" name="couples-occasion" value="yes"> Yes</label><label>Tell Reception about the occasion<textarea data-couples-occasion maxlength="160" rows="2" placeholder="For example: anniversary" disabled></textarea></label></fieldset>
      <details class="terms"><summary>Read Shiloh’s Booking Policy &amp; Terms <span class="terms__hint">Tap to open</span></summary><div class="policy">${webPolicyHtml(options.bookingPolicyText)}</div></details>
      <label class="confirm-label"><input type="checkbox" data-couples-policy><span>I have read and accept Shiloh’s Booking Policy &amp; Terms for this booking for two.</span></label>
      <p class="status" data-couples-confirm-status role="status" aria-live="polite"></p><div class="actions"><button class="button button--primary" type="button" data-couples-submit disabled>Send booking for two</button></div>
    </div></section>
    <section class="step" data-couples-step="5" hidden><div class="success-card"><div class="success-mark">✓</div><h2>Booking for two requested.</h2><p data-couples-success></p><div class="actions"><a class="button button--primary" href="/my-shiloh/#bookings">View My Shiloh bookings</a><a class="button button--soft" href="/my-shiloh/">Back to My Shiloh</a></div></div></section>
  </main>`;
  return renderMyShilohBookingPage(options)
    .replace(/<main class="shell"[\s\S]*?<\/main>/, main)
    .replace(/<script src="\/my-shiloh\/assets\/booking.js[^>]*><\/script>/, '<script src="/my-shiloh/assets/couples-booking.js?v=20261005" defer></script>')
    .replace('</style>', '.date-card select{width:100%;min-height:48px;padding:10px;border:1px solid #bdc8c0;border-radius:11px;background:white;font:inherit;font-size:16px}.date-card{min-width:0;display:grid;gap:10px}.date-card legend{font-weight:850}.date-card input:not([type="checkbox"]){width:100%}[data-my-shiloh-couples] [hidden]{display:none}.date-card .confirm-label{font-weight:400}.date-card p{font-size:14px;overflow-wrap:anywhere}</style>');
}
module.exports = { renderMyShilohCouplesBookingPage };
