'use strict';

const { STANDARD_HOSPITALITY } = require('../config/clinicFaqPolicy');

function escapeHtml(value = '') {
  return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')
    .replaceAll('"','&quot;').replaceAll("'",'&#039;');
}

function renderPlanningRequestPage({ clientFirstName = '', csrfToken = '', practitioners = [], requests = [], humanWhatsAppNumber = '', serviceDetail = '' } = {}) {
  const suppliedDigits = String(humanWhatsAppNumber || '').replace(/\D/g, '');
  const humanDigits = /^0[678]\d{8}$/.test(suppliedDigits) ? `27${suppliedDigits.slice(1)}`
    : /^27[678]\d{8}$/.test(suppliedDigits) ? suppliedDigits : '';
  const humanLink = humanDigits ? `<a href="https://wa.me/${humanDigits}?text=${encodeURIComponent('Hi Reception, I sent a planning request in My Shiloh and would like to speak with a person.')}" rel="noopener noreferrer">Message Reception on WhatsApp</a>` : '';
  const options = practitioners.map(item => `<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)}</option>`).join('');
  const history = requests.map(item => `<li><strong>${escapeHtml(item.request_kind === 'group' ? 'Group visit' : 'Flexible visit')}</strong> · ${escapeHtml(item.service_name || item.service_detail)}<br><span>${escapeHtml(item.status === 'planning' ? 'Reception is planning this with you.' : item.status === 'requested' ? 'Received by Reception; no appointment is confirmed.' : item.status === 'arranged' ? 'Reception arranged this visit; check your booking in My Shiloh.' : 'Reception could not arrange this request.')}</span></li>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><title>Plan a visit | My Shiloh</title><style>
:root{--ink:#23342d;--muted:#66736c;--cream:#f8f4ec;--leaf:#244c3d;--line:#d9dfd8}*{box-sizing:border-box}body{margin:0;background:var(--cream);color:var(--ink);font:16px/1.5 Inter,system-ui,sans-serif}.shell{width:min(680px,calc(100% - 28px));margin:auto;padding:24px 0 70px}.back{color:var(--leaf);font-weight:750;text-decoration:none;display:inline-flex;align-items:center;min-height:44px}h1,h2{font-family:Georgia,serif;font-weight:500}h1{font-size:clamp(34px,7vw,48px);line-height:1.1;margin:24px 0 10px}p{color:var(--muted)}form,.success{background:#fffdfa;border:1px solid var(--line);border-radius:18px;padding:clamp(18px,5vw,30px);display:grid;gap:19px}fieldset{border:0;padding:0;margin:0;display:grid;gap:9px;min-width:0}legend,label>span{font-weight:750}label{display:grid;gap:6px}label.choice{display:flex;align-items:center;gap:9px;min-height:42px;font-weight:650}input:not([type=radio]),select,textarea{width:100%;min-height:48px;border:1px solid #bac8bd;border-radius:10px;padding:10px 12px;background:#fff;color:var(--ink);font:inherit;font-size:16px}textarea{min-height:96px;resize:vertical}input[type=radio]{width:20px;height:20px;accent-color:var(--leaf)}small{color:var(--muted)}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.notice{background:#e7eee7;border-radius:12px;padding:14px;color:var(--ink);font-size:14px}.notice p{margin:5px 0 0;color:var(--ink)}.button{border:0;border-radius:11px;background:var(--leaf);color:white;min-height:48px;padding:10px 17px;font:inherit;font-weight:750;cursor:pointer;text-align:center;text-decoration:none}.button:disabled{opacity:.55;cursor:wait}.status{min-height:1.4em}.status[data-tone=error]{color:#8a413b}.success[hidden],[hidden]{display:none!important}:focus-visible{outline:3px solid #8a632f;outline-offset:3px}@media(max-width:520px){.row{grid-template-columns:1fr}}
</style></head><body><main class="shell" data-planning-page data-csrf="${escapeHtml(csrfToken)}"><a class="back" href="/my-shiloh/book">← Back to booking</a><h1>Let’s plan your visit, ${escapeHtml(clientFirstName)}.</h1><p>For a flexible time or a group experience, tell us what you have in mind. Reception will arrange the details with you. Nothing is booked or charged yet.</p><form data-planning-form>
<fieldset><legend>What would you like to plan?</legend><label class="choice"><input type="radio" name="kind" value="flexible" required checked> A visit with a flexible time</label><label class="choice"><input type="radio" name="kind" value="group" required> A group visit or tailored event</label></fieldset>
<label><span>Treatment or experience you have in mind</span><textarea name="serviceDetail" maxlength="160" required placeholder="Tell us about the treatment or experience">${escapeHtml(String(serviceDetail).slice(0, 160))}</textarea></label>
<div class="row"><label><span>Preferred date (optional)</span><input type="date" name="preferredDate"></label><label><span>Time of day (optional)</span><select name="preferredDaypart"><option value="">I’m flexible</option><option value="morning">Morning</option><option value="afternoon">Afternoon</option><option value="any">Any time</option></select></label></div>
<label><span>Preferred practitioner (optional)</span><select name="practitionerId"><option value="">Anyone suitable</option>${options}</select></label>
<label data-group-guests hidden><span>About how many guests?</span><input type="number" name="guestCount" min="2" step="1" inputmode="numeric"></label>
<fieldset><legend>Is this for a special occasion?</legend><label class="choice"><input type="radio" name="specialOccasion" value="yes" required> Yes</label><label class="choice"><input type="radio" name="specialOccasion" value="no" required> No</label></fieldset>
<label data-occasion-detail hidden><span>Tell us about the occasion</span><input type="text" name="occasionNote" maxlength="160" placeholder="For example, a birthday or anniversary"></label>
<label><span>Anything else Reception should know? (optional)</span><textarea name="clientNote" maxlength="500" placeholder="Your flexibility, ideas or questions"></textarea></label>
<div class="notice"><strong>Shiloh will plan this with you.</strong><p>Tailored group packages and special events are available upon request. ${escapeHtml(STANDARD_HOSPITALITY)} Any additional event arrangements will be discussed with Reception.</p></div>
<p class="status" role="status" aria-live="polite" data-planning-status></p><button class="button" type="submit" data-planning-submit>Send to Reception</button></form>
<div class="success" hidden data-planning-success><h2>We’ve received your request.</h2><p>Reception will plan the details with you. This is not a confirmed appointment.</p>${humanLink ? `<p>Would you prefer to speak with a person? ${humanLink}. Your request is already with Reception.</p>` : ''}<a class="button" href="/my-shiloh/#bookings">View My Shiloh</a></div>
${history ? `<section aria-labelledby="your-requests-title"><h2 id="your-requests-title">Your planning requests</h2><ul>${history}</ul><p>Your confirmed appointments remain in My Shiloh Bookings.</p></section>` : ''}</main><script src="/my-shiloh/assets/planning-request.js?v=20260927-sh05-v1" defer></script></body></html>`;
}

module.exports = { renderPlanningRequestPage };
