'use strict';

const { workspaceShellStyles, renderWorkspaceNavigation } = require('./workspaceShell');

function esc(value=''){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function rand(value){return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(Number(value||0));}
function date(value){return new Intl.DateTimeFormat('en-ZA',{dateStyle:'medium',timeStyle:'short',timeZone:'Africa/Johannesburg'}).format(new Date(value));}
const styles=`:root{--green:#24483a;--sage:#e8efe9;--cream:#f7f4ed;--ink:#24342e;--muted:#65736c;--line:#d9e1db}*{box-sizing:border-box}body{margin:0;background:var(--cream);color:var(--ink);font-family:Inter,system-ui,-apple-system,sans-serif}.rewards-shell{width:min(940px,100%);margin:auto;padding:22px}.head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:18px}.head h1{margin:3px 0;font-size:clamp(1.7rem,5vw,2.5rem);line-height:1.05}.head p{color:var(--muted);max-width:620px}.back{color:var(--green);font-weight:800;min-height:44px;display:inline-flex;align-items:center}.balance-card{display:grid;grid-template-columns:1fr auto;gap:18px;align-items:center;padding:24px;border-radius:22px;background:var(--green);color:#fff;box-shadow:0 12px 28px rgba(36,72,58,.14)}.balance-card small,.eyebrow{font-size:.72rem;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.balance-card strong{display:block;font-size:clamp(2rem,8vw,3.4rem);margin:4px 0}.balance-card p{margin:0;color:#dbe8e0}.ring{width:90px;height:90px;border-radius:50%;display:grid;place-items:center;border:8px solid rgba(255,255,255,.24);font-weight:850}.grid{display:grid;grid-template-columns:1.05fr .95fr;gap:16px;margin-top:16px}.card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:19px}.card h2{font-size:1.08rem;margin:0 0 12px}.booking{display:grid;gap:10px;padding:13px 0;border-top:1px solid var(--line)}.booking:first-of-type{border:0}.booking form{display:grid;grid-template-columns:minmax(110px,1fr) auto;gap:8px}.booking input,.adjust input,.adjust select{min-height:44px;border:1px solid #bdcbc1;border-radius:10px;padding:9px;font:inherit}.button{min-height:44px;border:0;border-radius:10px;padding:10px 14px;background:var(--green);color:#fff;font:inherit;font-weight:850;cursor:pointer}.button:disabled{opacity:.45;cursor:not-allowed}.history{list-style:none;padding:0;margin:0;display:grid;gap:8px}.history li{display:flex;justify-content:space-between;gap:12px;padding:11px;border-radius:11px;background:#f7faf7}.history span{display:grid;gap:3px}.history small,.muted{color:var(--muted)}.positive{color:#286a45}.negative{color:#9a493e}.status{min-height:20px;color:var(--green);font-weight:750}.adjust{display:grid;grid-template-columns:1fr 1fr 1fr;gap:9px}.adjust .wide{grid-column:1/-1}.wallets{width:100%;border-collapse:collapse}.wallets th,.wallets td{text-align:left;padding:11px 8px;border-bottom:1px solid var(--line)}.wallets th{font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}@media(max-width:720px){.rewards-shell{padding:14px}.head{display:grid}.balance-card{grid-template-columns:1fr}.ring{width:70px;height:70px}.grid{grid-template-columns:1fr}.booking form,.adjust{grid-template-columns:1fr}.wallets{display:block;overflow-x:auto}.card{padding:15px}}`;

function renderClientRewardsPage({model,csrfToken,clientScriptPath='/my-shiloh/rewards/client.js'}={}){
  const balance=model.wallet.balance,threshold=model.policy.unlockThreshold,progress=Math.min(100,Math.max(0,balance/threshold*100));
  const bookings=model.appointments.map(item=>`<article class="booking"><div><strong>${esc(item.service_name)}</strong><div class="muted">${esc(date(item.starts_at))}</div></div><form data-reward-form data-appointment-id="${item.id}"><label><span class="sr-only">Reward amount</span><input name="amount" type="number" min="0.01" max="${esc(balance.toFixed(2))}" step="0.01" value="${esc(Math.min(balance,Number(item.total_price||balance)).toFixed(2))}" ${model.wallet.unlocked?'':'disabled'}></label><button class="button" ${model.wallet.unlocked?'':'disabled'}>Use rewards</button></form></article>`).join('');
  const history=model.entries.map(item=>`<li><span><strong>${esc(item.notes||item.entry_type.replaceAll('_',' '))}</strong><small>${esc(date(item.created_at))}</small></span><b class="${Number(item.signed_amount)>=0?'positive':'negative'}">${Number(item.signed_amount)>=0?'+':'−'}${esc(rand(Math.abs(Number(item.signed_amount))))}</b></li>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Shiloh Rewards — My Shiloh</title><style>${styles}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}</style><script src="${esc(clientScriptPath)}" defer></script></head><body><main class="rewards-shell" data-rewards-page data-csrf="${esc(csrfToken)}"><header class="head"><div><div class="eyebrow">My Shiloh</div><h1>Shiloh Rewards</h1><p>We add 5% of every completed, paid treatment to your private rewards balance.</p></div><a class="back" href="/my-shiloh/#wallet">Back to Wallet</a></header><section class="balance-card"><div><small>Your rewards balance</small><strong>${esc(rand(balance))}</strong><p>${model.wallet.unlocked?'Ready whenever you choose to use it.':`${esc(rand(Math.max(0,threshold-balance)))} to go before your rewards unlock.`}</p></div><div class="ring" aria-label="${Math.round(progress)} percent toward unlock">${Math.round(progress)}%</div></section><p class="status" role="status" data-rewards-status></p><div class="grid"><section class="card"><h2>Use your rewards</h2>${bookings||'<p class="muted">Your next eligible booking will appear here.</p>'}</section><section class="card"><h2>Your reward history</h2><ul class="history">${history||'<li>No rewards activity yet.</li>'}</ul></section></div></main></body></html>`;
}

function renderWorkspaceRewardsPage({model,csrfToken,displayName='',clientScriptPath='/calendar/rewards/client.js'}={}){
  const rows=model.wallets.map(item=>`<tr><td><strong>${esc(item.name)}</strong><br><small>${esc(item.normalized_mobile)}</small></td><td>${esc(rand(item.balance))}</td><td>${item.latest_activity?esc(date(item.latest_activity)):'—'}</td></tr>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Shiloh Rewards — Workspace</title><style>${workspaceShellStyles()}${styles}.workspace-main .rewards-shell{margin:0 auto}</style><script src="${esc(clientScriptPath)}" defer></script></head><body><div class="workspace-frame">${renderWorkspaceNavigation({active:'rewards',displayName,dashboardHref:'/calendar/workspace',calendarHref:'/calendar/read-only',clientsHref:'/calendar/clients',messagesHref:'/calendar/messages',staffHref:'/calendar/team',servicesHref:'/calendar/services',reportsHref:'/calendar/reports',clinicHoursHref:'/calendar/clinic-hours',vouchersHref:'/calendar/vouchers',rewardsHref:'/calendar/rewards'})}<main class="workspace-main"><div class="rewards-shell" data-workspace-rewards data-csrf="${esc(csrfToken)}"><header class="head"><div><div class="eyebrow">Client care</div><h1>Shiloh Rewards</h1><p>Clients earn ${esc(model.policy.earnRate)}% after a treatment is completed and paid. Rewards unlock at ${esc(rand(model.policy.unlockThreshold))} and do not expire.</p></div></header>${model.authority.canManage?`<section class="card"><h2>Add a goodwill reward or correction</h2><form class="adjust" data-adjust-form><label>Client name or mobile<input name="clientSearch" autocomplete="off" required></label><label>Action<select name="direction"><option value="add">Add credit</option><option value="remove">Remove credit</option></select></label><label>Amount (R)<input name="amount" type="number" min="0.01" step="0.01" required></label><label class="wide">Note <span class="muted">(optional)</span><input name="notes" maxlength="240"></label><button class="button wide">Save adjustment</button></form><p class="status" role="status" data-adjust-status></p></section>`:''}<section class="card" style="margin-top:16px"><h2>Client balances</h2><table class="wallets"><thead><tr><th>Client</th><th>Balance</th><th>Latest activity</th></tr></thead><tbody>${rows||'<tr><td colspan="3">No rewards have been earned yet.</td></tr>'}</tbody></table></section></div></main></div></body></html>`;
}

function clientRewardsScript(){return `(()=>{'use strict';const root=document.querySelector('[data-rewards-page]'),status=root&&root.querySelector('[data-rewards-status]');if(!root)return;root.addEventListener('submit',async event=>{const form=event.target.closest('[data-reward-form]');if(!form)return;event.preventDefault();const amount=form.elements.amount.value;if(!confirm('Use '+new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(Number(amount))+' of your Shiloh Rewards on this booking?'))return;status.textContent='Applying your rewards…';try{const response=await fetch('/my-shiloh/api/rewards/redeem',{method:'POST',headers:{'Content-Type':'application/json','X-Shiloh-CSRF-Token':root.dataset.csrf},body:JSON.stringify({appointmentId:form.dataset.appointmentId,amount,operationId:crypto.randomUUID().replaceAll('-','')})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Your rewards could not be applied.');status.textContent='Your Shiloh Rewards were applied. Refreshing…';location.reload();}catch(error){status.textContent=error.message;}});})();`;}
function workspaceRewardsScript(){return `(()=>{'use strict';const root=document.querySelector('[data-workspace-rewards]'),form=root&&root.querySelector('[data-adjust-form]'),status=root&&root.querySelector('[data-adjust-status]');if(!form)return;form.addEventListener('submit',async event=>{event.preventDefault();status.textContent='Saving…';try{const response=await fetch('/calendar/rewards/adjust',{method:'POST',headers:{'Content-Type':'application/json','X-Shiloh-CSRF-Token':root.dataset.csrf},body:JSON.stringify({...Object.fromEntries(new FormData(form)),operationId:crypto.randomUUID().replaceAll('-','')})});const data=await response.json();if(!response.ok)throw new Error(data.error||'The adjustment could not be saved.');status.textContent='Reward balance updated. Refreshing…';location.reload();}catch(error){status.textContent=error.message;}});})();`;}

module.exports={renderClientRewardsPage,renderWorkspaceRewardsPage,clientRewardsScript,workspaceRewardsScript};
