'use strict';

// Shared Shiloh confirmation surface for Workspace and My Shiloh. Callers supply the action and its consequence;
// the server remains the authority for whether the action is allowed.
function confirmationStyles() {
  return `.shiloh-confirm{width:min(420px,calc(100% - 32px));max-height:calc(100dvh - 32px);border:1px solid var(--line-strong,#d5ded7);border-radius:20px;padding:0;background:var(--panel,#fffdf9);color:var(--ink,#24382e);box-shadow:0 24px 70px rgba(20,40,30,.24)}.shiloh-confirm::backdrop{background:rgba(20,40,30,.48)}.shiloh-confirm__body{padding:24px}.shiloh-confirm h2{margin:7px 0 9px;font-size:1.3rem;line-height:1.3}.shiloh-confirm p{margin:0;color:var(--muted,#54675c);line-height:1.55}.shiloh-confirm__actions{display:flex;justify-content:flex-end;flex-wrap:wrap;gap:9px;margin-top:24px}.shiloh-confirm__actions .button{min-height:48px;border:1px solid #d5ded7;border-radius:999px;padding:11px 18px;background:#fffdf9;color:#24382e;font:inherit;font-weight:750;cursor:pointer}.shiloh-confirm__actions .button.danger{background:#843f35;border-color:#843f35;color:#fff}.shiloh-confirm__actions .button.primary{background:#2f493a;border-color:#2f493a;color:#fff}.shiloh-confirm :focus-visible{outline:3px solid #977b4d;outline-offset:3px}.shiloh-confirm .eyebrow{font-size:.75rem;font-weight:800;letter-spacing:.1em;color:#54675c}.shiloh-confirm{font-family:inherit}.shiloh-confirm,.shiloh-confirm *{box-sizing:border-box}@media(max-width:480px){.shiloh-confirm__body{padding:20px}.shiloh-confirm__actions{display:grid;grid-template-columns:minmax(0,1fr);justify-content:stretch}.shiloh-confirm__actions .button{width:100%}}.shiloh-confirm--refresh{max-width:calc(100% - 32px)}.shiloh-confirm--refresh .eyebrow{display:none}.shiloh-confirm--refresh .shiloh-confirm__body{padding:18px}.shiloh-confirm--refresh h2{margin:0 0 8px;overflow-wrap:anywhere}.shiloh-confirm--refresh .shiloh-confirm__actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.shiloh-confirm--refresh .shiloh-confirm__actions .button{flex:1 1 auto;width:auto;min-height:48px;padding:10px 16px;max-width:100%;overflow-wrap:anywhere}`;
}

function confirmationMarkup() {
  return `<dialog class="shiloh-confirm" data-shiloh-confirm aria-labelledby="shiloh-confirm-title" aria-describedby="shiloh-confirm-copy"><div class="shiloh-confirm__body"><span class="eyebrow">Please confirm</span><h2 id="shiloh-confirm-title" data-shiloh-confirm-title></h2><p id="shiloh-confirm-copy" data-shiloh-confirm-copy></p><div class="shiloh-confirm__actions"><button class="button" type="button" data-shiloh-confirm-cancel></button><button class="button danger" type="button" data-shiloh-confirm-action></button></div></div></dialog>`;
}

function confirmationClientScript({ externalStyles = false } = {}) {
  return `(function(){'use strict';
if(window.ShilohConfirm)return;
if(!document.querySelector('[data-shiloh-confirm]')){var host=document.createElement('div');host.innerHTML=${JSON.stringify(confirmationMarkup())};document.body.appendChild(host.firstElementChild);}
${externalStyles ? '' : `var style=document.createElement('style');style.textContent=${JSON.stringify(confirmationStyles())};document.head.appendChild(style);`}
var dialog=document.querySelector('[data-shiloh-confirm]');
var title=dialog.querySelector('[data-shiloh-confirm-title]'),copy=dialog.querySelector('[data-shiloh-confirm-copy]'),cancel=dialog.querySelector('[data-shiloh-confirm-cancel]'),action=dialog.querySelector('[data-shiloh-confirm-action]');
window.ShilohConfirm=function(options){if(dialog.open)return Promise.resolve(false);var previous=document.activeElement;dialog.classList.toggle('shiloh-confirm--refresh',options.layout==='refresh'&&options.danger===false);title.textContent=String(options.title||'Confirm action?');copy.textContent=String(options.copy||'');cancel.textContent=String(options.cancel||'Keep');action.textContent=String(options.action||'Confirm');action.classList.toggle('danger',options.danger!==false);action.classList.toggle('primary',options.danger===false);
return new Promise(function(resolve){var decided=false;function settle(value){if(decided)return;decided=true;dialog.close();resolve(value);}function onCancel(event){event.preventDefault();settle(false);}function onClose(){cleanup();if(!decided){decided=true;resolve(false);}if(previous&&previous.isConnected&&typeof previous.focus==='function')previous.focus({preventScroll:true});}function cleanup(){dialog.removeEventListener('cancel',onCancel);dialog.removeEventListener('close',onClose);cancel.removeEventListener('click',onKeep);action.removeEventListener('click',onAction);}function onKeep(){settle(false);}function onAction(){settle(true);}dialog.addEventListener('cancel',onCancel);dialog.addEventListener('close',onClose);cancel.addEventListener('click',onKeep);action.addEventListener('click',onAction);dialog.showModal();cancel.focus({preventScroll:true});});};
})();`;
}

module.exports = { confirmationStyles, confirmationMarkup, confirmationClientScript };
