// Fixed descriptions for existing Shiloh operational permissions; no independent grant store.
const ACCESS_CAPABILITIES = Object.freeze({
  "appointment:view": Object.freeze({ label: "View appointments and Dashboard", description: "See appointments and the Workspace dashboard within existing access boundaries." }),
  "appointment:create": Object.freeze({ label: "Create bookings", description: "Create appointments for permitted practitioners and services." }),
  "appointment:record_past": Object.freeze({ label: "Record past appointments", description: "Record past visits; existing permitted-client restrictions still apply." }),
  "appointment:adjust_end": Object.freeze({ label: "Adjust appointment end time", description: "Change the end time of a permitted appointment." }),
  "booking:update": Object.freeze({ label: "Complete or mark visits no-show", description: "Mark permitted appointments complete or no-show." }),
  "calendar:booking:reschedule": Object.freeze({ label: "Reschedule bookings", description: "Move permitted bookings to a different time." }),
  "calendar:booking:cancel": Object.freeze({ label: "Cancel bookings", description: "Cancel permitted bookings." }),
  "calendar:booking:reassign": Object.freeze({ label: "Reassign practitioners", description: "Change the practitioner on permitted bookings." }),
  "client:lookup": Object.freeze({ label: "View clients and communication evidence", description: "Find and view permitted client records and their communication history." }),
  "client:manage": Object.freeze({ label: "Add, edit and archive clients", description: "Add, update and archive permitted client records." }),
  "client:notify": Object.freeze({ label: "Send ordinary client notifications", description: "Send permitted ordinary client notifications through available channels." }),
  "client:delete": Object.freeze({ label: "Permanently delete clients", description: "Permanently delete permitted client records where the operation is available." }),
  "services:view": Object.freeze({ label: "View services", description: "See services within the existing service boundary." }),
  "services:create": Object.freeze({ label: "Add services", description: "Create services using the existing catalogue controls." }),
  "services:manage": Object.freeze({ label: "Manage the business-wide service catalogue and practitioner assignments", description: "Edit permitted services and practitioner assignments." }),
  "service:pricing": Object.freeze({ label: "Manage pricing", description: "Change permitted service prices." }),
  "staff:services:view": Object.freeze({ label: "View staff service assignments", description: "See practitioner service assignments." }),
  "schedule:manage": Object.freeze({ label: "Manage clinic hours, closures and schedules", description: "Change clinic hours, closures and working schedules." }),
  "staff:view": Object.freeze({ label: "View Staff", description: "See Staff profiles." }),
  "staff:manage": Object.freeze({ label: "Manage Staff profiles", description: "Add and update Staff profiles." }),
  "staff_access:manage": Object.freeze({ label: "Manage Workspace access", description: "Manage other people\u2019s Workspace permissions. Clinic administrator authority is still required for individual access changes." }),
  "staff_auth:reset": Object.freeze({ label: "Reset staff authentication", description: "Use protected staff sign-in recovery; its existing verification requirements remain." }),
  "walkin:create": Object.freeze({ label: "Register walk-in clients", description: "Register walk-in clients." }),
  "loyalty:redeem": Object.freeze({ label: "Redeem loyalty rewards", description: "Redeem eligible client rewards." }),
  "loyalty:view": Object.freeze({ label: "View Shiloh Rewards", description: "See Shiloh Rewards balances and history." }),
  "loyalty:manage": Object.freeze({ label: "Adjust Shiloh Rewards", description: "Adjust Shiloh Rewards using the existing audited controls." }),
  "overflow:visible": Object.freeze({ label: "View overflow availability", description: "See overflow appointment availability." }),
  "reports:view_all": Object.freeze({ label: "View clinic-wide reports", description: "View reports across the clinic rather than only assigned work." }),
  "schedule:view": Object.freeze({ label: "View clinic hours", description: "See clinic opening and booking hours." }),
  "schedule:availability_manage": Object.freeze({ label: "Manage assigned availability and leave", description: "Manage availability and leave within the existing practitioner boundary." }),
  "forms:view": Object.freeze({ label: "View permitted client forms", description: "Read permitted client consultation and clinical forms." }),
  "forms:clinical_manage": Object.freeze({ label: "Manage permitted clinical forms", description: "Complete and update permitted clinical forms." }),
  "service_categories:manage": Object.freeze({ label: "Manage treatment categories", description: "Create and update treatment categories." }),
  "staff_earnings:manage": Object.freeze({ label: "View staff earnings and manage future commission rates", description: "View earnings and change future commission rates; requires clinic administrator access and appointment viewing." }),
  "payment:refund": Object.freeze({ label: "Issue permitted payment refunds", description: "Record permitted refunds; payment viewing and existing refund checks still apply." }),
  "payment:view": Object.freeze({ label: "View payments", description: "See permitted appointment payments and balances." }),
  "payment:manage": Object.freeze({ label: "Manage payments", description: "Use existing payment management operations where available." }),
  "voucher:view": Object.freeze({ label: "View vouchers", description: "See gift vouchers and their history." }),
  "voucher:issue": Object.freeze({ label: "Issue vouchers", description: "Issue gift vouchers using the existing voucher controls." }),
  "voucher:manage": Object.freeze({ label: "Manage vouchers", description: "Manage existing gift vouchers." }),
  "voucher:redeem": Object.freeze({ label: "Redeem vouchers", description: "Redeem valid gift vouchers." }),
  "appointment:group:discount": Object.freeze({ label: "Apply permitted group booking discounts", description: "Apply permitted group booking discounts." }),
  "appointment:couples:discount": Object.freeze({ label: "Apply permitted couples booking discounts", description: "Apply permitted couples booking discounts." }),
  "problem_reports:manage": Object.freeze({ label: "Review and manage reported problems", description: "Review and resolve reported problems." }),
  "payment:collect": Object.freeze({ label: "Request and record payments", description: "Create payment requests and record permitted payments; payment viewing is also required." }),
  "booking_requests:manage": Object.freeze({ label: "Manage Reception booking requests", description: "Accept, plan, decline and propose alternatives for client requests in the existing Reception queue. Reception role and coordination boundaries still apply; Reception also needs Create bookings." }),
});
module.exports = { ACCESS_CAPABILITIES };
