const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {money,CAPABILITIES}=require('../src/services/bookingPayments');
const {canonicalHash,configured,createOzowPaymentProvider}=require('../src/services/ozowPaymentProvider');
const {renderCalendarPaymentPage,calendarPaymentLinkClientScript}=require('../src/presentation/calendarPaymentsUx');
const {evaluateCalendarAuthority}=require('../src/services/calendarAuthorization');

const root=path.join(__dirname,'..');
test('payment schema owns one ordinary or linked booking subject and immutable evidence',()=>{const sql=fs.readFileSync(path.join(root,'migrations/123_booking_payment_foundation.sql'),'utf8');assert.match(sql,/booking_payment_accounts_one_subject/);assert.match(sql,/payment_ledger_entries/);assert.match(sql,/payment_provider_events/);assert.match(sql,/authorized_manual/);assert.match(sql,/payment:collect/);assert.doesNotMatch(sql,/UPDATE appointments|UPDATE appointment_groups/);});
test('Rand amounts are exact and reject excess precision or signs',()=>{assert.equal(money('740.5',{positive:true}),'740.50');assert.throws(()=>money('-1',{positive:true}));assert.throws(()=>money('1.001',{positive:true}));});
test('payment capabilities remain bounded',()=>{assert.deepEqual(CAPABILITIES,{VIEW:'payment:view',COLLECT:'payment:collect',REFUND:'payment:refund'});});
test('payment authority is included when the payment service resolves an operator',()=>{const authority=evaluateCalendarAuthority({id:9,admin_active:true,staff_id:null,staff_status:null,calendar_scope:'all_business',service_scope:'all_services',permissions:{'appointment:view':true,'payment:view':true,'payment:collect':true,'payment:refund':true}},{additionalCapabilities:Object.values(CAPABILITIES)});assert.ok(authority);assert.deepEqual(authority.capabilities.sort(),['appointment:view','payment:collect','payment:refund','payment:view']);});
test('Jean-Pierre payment access migration is narrow and does not grant refunds',()=>{const sql=fs.readFileSync(path.join(root,'migrations/130_jean_pierre_payment_collection_access.sql'),'utf8');assert.match(sql,/LOWER\(TRIM\(display_name\)\) = 'jean-pierre'/);assert.match(sql,/payment:view/);assert.match(sql,/payment:collect/);assert.doesNotMatch(sql,/payment:refund/);});
test('payment subject lookup uses the actual legacy contact schema and CRM V2 fallback',()=>{const source=fs.readFileSync(path.join(root,'src/services/bookingPayments.js'),'utf8');assert.doesNotMatch(source,/c\.normalized_mobile/);assert.match(source,/FROM client_contacts cc/);assert.match(source,/LEFT JOIN crm_v2_clients v2/);assert.match(source,/clientMobile: String\(row\.client_mobile/);});
test('Ozow return pages never claim payment truth',()=>{const source=fs.readFileSync(path.join(root,'src/routes/paymentReturns.js'),'utf8');const ux=fs.readFileSync(path.join(root,'src/presentation/paymentReturnUx.js'),'utf8');assert.match(source,/return\/success/);assert.match(source,/return\/cancelled/);assert.match(source,/return\/error/);assert.doesNotMatch(source,/handleOzowNotification/);assert.match(ux,/only be marked received after Shiloh verifies/);});
test('Ozow adapter fails closed until every merchant boundary is configured',()=>{assert.equal(configured({}),false);const provider=createOzowPaymentProvider({env:{},fetchImpl:async()=>{throw new Error('must not call');}});assert.equal(provider.configured(),false);assert.rejects(()=>provider.createPaymentLink({requestKey:'request_123',amount:'10.00',bankReference:'SHILOH'}),/not configured/i);assert.equal(canonicalHash([' SITE ','ZAR','10.00'],' secret '),canonicalHash(['site','zar','10.00'],'secret'));});
test('linked payment UI supports split balance and does not claim booking confirmation',()=>{const html=renderCalendarPaymentPage({model:{subject:{appointmentId:701,groupId:55},payment:{state:'partially_paid',amountDue:'1240.00',netPaid:'500.00',outstanding:'740.00',requests:[],entries:[]},authority:{canCollect:true,canRefund:false,ozowConfigured:false}}});assert.match(html,/Linked booking #55/);assert.match(html,/R\s?740[,.]00/);assert.match(html,/separate requests for a couple or group/);assert.match(html,/Payment never changes attendance or booking status/);assert.match(calendarPaymentLinkClientScript(),/calendar\/payments\/appointments/);});
