-- One customer-facing Couples Massage booking is represented by two canonical
-- appointments so that each guest keeps an independent CRM profile, history,
-- practitioner assignment and notification trail.

CREATE TABLE IF NOT EXISTS appointment_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_type TEXT NOT NULL CHECK (group_type IN ('couples_massage')),
  service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
  location_id BIGINT REFERENCES locations(id) ON DELETE SET NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled','confirmed','completed','cancelled','partially_changed')),
  total_price NUMERIC(12,2),
  currency CHAR(3) NOT NULL DEFAULT 'ZAR',
  source TEXT NOT NULL DEFAULT 'shiloh_calendar_couples',
  created_by_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT appointment_groups_time_check CHECK (ends_at > starts_at)
);

CREATE TABLE IF NOT EXISTS appointment_group_members (
  group_id BIGINT NOT NULL REFERENCES appointment_groups(id) ON DELETE CASCADE,
  appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  guest_position SMALLINT NOT NULL CHECK (guest_position IN (1,2)),
  allocated_price NUMERIC(12,2),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (group_id, guest_position),
  UNIQUE (appointment_id)
);

CREATE INDEX IF NOT EXISTS idx_appointment_groups_window
  ON appointment_groups(starts_at, ends_at);

CREATE TABLE IF NOT EXISTS admin_couples_booking_sessions (
  admin_id BIGINT PRIMARY KEY REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  state TEXT NOT NULL DEFAULT 'confirm' CHECK (state IN ('confirm')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE appointment_groups IS
  'Logical booking parent for operations that must remain grouped while retaining separate canonical appointment children.';
COMMENT ON TABLE admin_couples_booking_sessions IS
  'Short-lived review draft. New CRM clients are deliberately not written until atomic final confirmation.';
