-- #995: provider-independent payment authority for ordinary and linked bookings.
-- Payment truth is deliberately separate from appointment/calendar/attendance truth.

CREATE TABLE IF NOT EXISTS booking_payment_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT REFERENCES appointments(id) ON DELETE RESTRICT,
  appointment_group_id BIGINT REFERENCES appointment_groups(id) ON DELETE RESTRICT,
  canonical_amount_due NUMERIC(12,2) NOT NULL CHECK (canonical_amount_due >= 0),
  currency CHAR(3) NOT NULL DEFAULT 'ZAR' CHECK (currency = 'ZAR'),
  pricing_revision TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT booking_payment_accounts_one_subject CHECK (
    (appointment_id IS NOT NULL)::integer + (appointment_group_id IS NOT NULL)::integer = 1
  )
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_payment_accounts_appointment
  ON booking_payment_accounts(appointment_id) WHERE appointment_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_payment_accounts_group
  ON booking_payment_accounts(appointment_group_id) WHERE appointment_group_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS payment_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_account_id BIGINT NOT NULL REFERENCES booking_payment_accounts(id) ON DELETE RESTRICT,
  request_key TEXT NOT NULL UNIQUE,
  provider TEXT NOT NULL CHECK (provider IN ('ozow')),
  provider_request_id TEXT,
  provider_payment_url TEXT,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  currency CHAR(3) NOT NULL DEFAULT 'ZAR' CHECK (currency = 'ZAR'),
  state TEXT NOT NULL DEFAULT 'created' CHECK (state IN (
    'created','link_issued','pending','paid','failed','cancelled','expired',
    'partially_refunded','refunded'
  )),
  payer_name TEXT,
  payer_mobile TEXT,
  expires_at TIMESTAMPTZ,
  created_by_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (provider, provider_request_id)
);

CREATE TABLE IF NOT EXISTS payment_ledger_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_account_id BIGINT NOT NULL REFERENCES booking_payment_accounts(id) ON DELETE RESTRICT,
  payment_request_id BIGINT REFERENCES payment_requests(id) ON DELETE RESTRICT,
  entry_type TEXT NOT NULL CHECK (entry_type IN ('payment','refund')),
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  currency CHAR(3) NOT NULL DEFAULT 'ZAR' CHECK (currency = 'ZAR'),
  method TEXT NOT NULL CHECK (method IN ('ozow','cash','card_machine','manual_eft')),
  evidence_kind TEXT NOT NULL CHECK (evidence_kind IN ('verified_provider','authorized_manual')),
  provider_transaction_id TEXT,
  operation_key TEXT UNIQUE,
  external_reference TEXT,
  actor_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  notes TEXT CHECK (notes IS NULL OR CHAR_LENGTH(notes) <= 240),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (method, provider_transaction_id, entry_type)
);

CREATE TABLE IF NOT EXISTS payment_provider_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL CHECK (provider IN ('ozow')),
  provider_event_key TEXT NOT NULL,
  payment_request_id BIGINT REFERENCES payment_requests(id) ON DELETE SET NULL,
  signature_verified BOOLEAN NOT NULL,
  payload_sha256 CHAR(64) NOT NULL,
  outcome TEXT NOT NULL CHECK (outcome IN ('accepted','duplicate','rejected','unmatched')),
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (provider, provider_event_key)
);

CREATE INDEX IF NOT EXISTS idx_payment_requests_account ON payment_requests(payment_account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_ledger_account ON payment_ledger_entries(payment_account_id, created_at DESC);

-- Payment operations are clinic/reception authority, not practitioner authority.
UPDATE staff_admin_accounts
   SET permissions = COALESCE(permissions, '{}'::jsonb)
                     || '{"payment:view":true,"payment:collect":true}'::jsonb,
       updated_at = NOW()
 WHERE active = TRUE
   AND business_role IN ('owner','booking_operator')
   AND calendar_scope = 'all_business'
   AND service_scope = 'all_services';

UPDATE staff_admin_accounts
   SET permissions = COALESCE(permissions, '{}'::jsonb)
                     || '{"payment:refund":true}'::jsonb,
       updated_at = NOW()
 WHERE active = TRUE
   AND business_role = 'owner'
   AND calendar_scope = 'all_business'
   AND service_scope = 'all_services';

COMMENT ON TABLE payment_ledger_entries IS
  'Immutable settlement/refund evidence. It never changes booking, attendance, Calendar or loyalty truth.';
COMMENT ON COLUMN booking_payment_accounts.canonical_amount_due IS
  'Snapshot of canonical appointment/group pricing when the payment account is opened; refreshed only before settlement.';
