-- Scoped Workspace client relationships.
--
-- One real person remains one canonical crm_v2_clients row. This table records
-- which business relationship may see and manage that person in Workspace.
-- A client may simultaneously belong to the clinic and one or more tenant
-- practitioners without duplicating the canonical identity or mobile number.

CREATE TABLE IF NOT EXISTS crm_v2_client_relationships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES crm_v2_clients(id) ON DELETE CASCADE,
  relationship_type TEXT NOT NULL
    CHECK (relationship_type IN ('clinic', 'tenant_staff')),
  owner_staff_id BIGINT REFERENCES staff(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'archived')),
  source TEXT NOT NULL CHECK (BTRIM(source) <> ''),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT crm_v2_client_relationship_owner_check CHECK (
    (relationship_type='clinic' AND owner_staff_id IS NULL)
    OR (relationship_type='tenant_staff' AND owner_staff_id IS NOT NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_crm_v2_client_relationship_clinic
  ON crm_v2_client_relationships(client_id)
  WHERE relationship_type='clinic';

CREATE UNIQUE INDEX IF NOT EXISTS uq_crm_v2_client_relationship_tenant
  ON crm_v2_client_relationships(client_id, owner_staff_id)
  WHERE relationship_type='tenant_staff';

CREATE INDEX IF NOT EXISTS idx_crm_v2_client_relationship_tenant_list
  ON crm_v2_client_relationships(owner_staff_id, status, client_id)
  WHERE relationship_type='tenant_staff';

CREATE INDEX IF NOT EXISTS idx_crm_v2_client_relationship_clinic_list
  ON crm_v2_client_relationships(status, client_id)
  WHERE relationship_type='clinic';

-- Existing tenant-owned appointment history becomes the tenant relationship.
INSERT INTO crm_v2_client_relationships
  (client_id, relationship_type, owner_staff_id, status, source)
SELECT DISTINCT a.crm_v2_client_id,
       'tenant_staff',
       visibility.owner_staff_id,
       c.status,
       'migration_127_tenant_appointment'
  FROM appointments a
  JOIN crm_v2_clients c ON c.id=a.crm_v2_client_id
  JOIN appointment_services aps ON aps.appointment_id=a.id
  JOIN service_visibility_policies visibility
    ON visibility.service_id=aps.service_id
   AND visibility.visibility_scope='tenant_private'
 WHERE a.crm_v2_client_id IS NOT NULL
   AND a.client_id IS NULL
ON CONFLICT (client_id, owner_staff_id)
  WHERE relationship_type='tenant_staff'
DO UPDATE SET
  status=EXCLUDED.status,
  updated_at=NOW();

-- Preserve the clinic's existing base unless the retained evidence says the
-- person has only tenant-private appointments. Clients with an ordinary clinic
-- service, an appointment without service rows, or no appointment history are
-- conservatively kept in the clinic relationship. A shared client gets both.
INSERT INTO crm_v2_client_relationships
  (client_id, relationship_type, owner_staff_id, status, source)
SELECT c.id,
       'clinic',
       NULL,
       c.status,
       'migration_127_clinic_preserve'
  FROM crm_v2_clients c
 WHERE NOT EXISTS (
         SELECT 1
           FROM appointments a_any
          WHERE a_any.crm_v2_client_id=c.id
            AND a_any.client_id IS NULL
       )
    OR EXISTS (
         SELECT 1
           FROM appointments a_clinic
          WHERE a_clinic.crm_v2_client_id=c.id
            AND a_clinic.client_id IS NULL
            AND (
              NOT EXISTS (
                SELECT 1 FROM appointment_services aps_any
                 WHERE aps_any.appointment_id=a_clinic.id
              )
              OR EXISTS (
                SELECT 1
                  FROM appointment_services aps_clinic
                  LEFT JOIN service_visibility_policies visibility
                    ON visibility.service_id=aps_clinic.service_id
                   AND visibility.visibility_scope='tenant_private'
                 WHERE aps_clinic.appointment_id=a_clinic.id
                   AND visibility.service_id IS NULL
              )
            )
       )
ON CONFLICT (client_id)
  WHERE relationship_type='clinic'
DO UPDATE SET
  status=EXCLUDED.status,
  updated_at=NOW();

-- Every newly written CRM V2 appointment service automatically establishes the
-- correct relationship. This covers public, internal, couples, group and other
-- booking writers without creating separate identity logic in each path.
CREATE OR REPLACE FUNCTION shiloh_sync_client_relationship_from_appointment_service()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_client_id BIGINT;
  v_owner_staff_id BIGINT;
BEGIN
  SELECT a.crm_v2_client_id
    INTO v_client_id
    FROM appointments a
   WHERE a.id=NEW.appointment_id
     AND a.client_id IS NULL;

  IF v_client_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT visibility.owner_staff_id
    INTO v_owner_staff_id
    FROM service_visibility_policies visibility
   WHERE visibility.service_id=NEW.service_id
     AND visibility.visibility_scope='tenant_private';

  IF v_owner_staff_id IS NOT NULL THEN
    INSERT INTO crm_v2_client_relationships
      (client_id, relationship_type, owner_staff_id, status, source)
    VALUES
      (v_client_id, 'tenant_staff', v_owner_staff_id, 'active', 'appointment_service')
    ON CONFLICT (client_id, owner_staff_id)
      WHERE relationship_type='tenant_staff'
    DO UPDATE SET
      status='active',
      source='appointment_service',
      updated_at=NOW();
  ELSE
    INSERT INTO crm_v2_client_relationships
      (client_id, relationship_type, owner_staff_id, status, source)
    VALUES
      (v_client_id, 'clinic', NULL, 'active', 'appointment_service')
    ON CONFLICT (client_id)
      WHERE relationship_type='clinic'
    DO UPDATE SET
      status='active',
      source='appointment_service',
      updated_at=NOW();
  END IF;

  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_sync_client_relationship_from_appointment_service
  ON appointment_services;
CREATE TRIGGER trg_sync_client_relationship_from_appointment_service
AFTER INSERT OR UPDATE OF service_id, appointment_id ON appointment_services
FOR EACH ROW
EXECUTE FUNCTION shiloh_sync_client_relationship_from_appointment_service();

-- Owner-authorized Marietjie client management. Runtime authority remains
-- generic and relationship-scoped; this migration only grants the existing
-- client:manage capability to the one expected tenant principal.
DO $$
DECLARE
  matched_principals INTEGER;
BEGIN
  SELECT COUNT(*)
    INTO matched_principals
    FROM staff_admin_accounts a
    JOIN staff s ON s.id=a.staff_id
   WHERE LOWER(TRIM(a.display_name))='marietjie'
     AND a.active=TRUE
     AND a.business_role='tenant_practitioner'
     AND a.staff_id IS NOT NULL
     AND s.status='active'
     AND COALESCE((a.permissions->>'client:lookup')::boolean,FALSE)=TRUE;

  IF matched_principals <> 1 THEN
    RAISE EXCEPTION 'expected exactly one active Marietjie tenant practitioner with client lookup authority, found %', matched_principals;
  END IF;

  UPDATE staff_admin_accounts
     SET permissions=COALESCE(permissions,'{}'::jsonb) || '{"client:manage":true}'::jsonb,
         updated_at=NOW()
   WHERE LOWER(TRIM(display_name))='marietjie'
     AND active=TRUE
     AND business_role='tenant_practitioner';
END $$;
