-- Workspace consultation forms foundation.
--
-- This migration creates versioned form templates and reusable question sections,
-- maps the first two forms to canonical service IDs, and creates assignment/status
-- metadata. It deliberately creates no public form route, sends no WhatsApp
-- message, stores no plaintext access token, and backfills no client answers.

CREATE TABLE IF NOT EXISTS consultation_form_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_key TEXT NOT NULL UNIQUE CHECK (BTRIM(section_key) <> ''),
  title TEXT NOT NULL CHECK (BTRIM(title) <> ''),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS consultation_form_section_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id BIGINT NOT NULL REFERENCES consultation_form_sections(id) ON DELETE RESTRICT,
  version_number INTEGER NOT NULL CHECK (version_number > 0),
  definition JSONB NOT NULL CHECK (jsonb_typeof(definition) = 'object'),
  source_label TEXT NOT NULL CHECK (BTRIM(source_label) <> ''),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (section_id, version_number)
);

CREATE TABLE IF NOT EXISTS consultation_form_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_key TEXT NOT NULL UNIQUE CHECK (BTRIM(template_key) <> ''),
  title TEXT NOT NULL CHECK (BTRIM(title) <> ''),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS consultation_form_template_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT NOT NULL REFERENCES consultation_form_templates(id) ON DELETE RESTRICT,
  version_number INTEGER NOT NULL CHECK (version_number > 0),
  consent_text TEXT NOT NULL CHECK (BTRIM(consent_text) <> ''),
  settings JSONB NOT NULL DEFAULT '{"signature_required":true}'::jsonb
    CHECK (jsonb_typeof(settings) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (template_id, version_number)
);

CREATE TABLE IF NOT EXISTS consultation_form_template_sections (
  template_version_id BIGINT NOT NULL REFERENCES consultation_form_template_versions(id) ON DELETE RESTRICT,
  section_version_id BIGINT NOT NULL REFERENCES consultation_form_section_versions(id) ON DELETE RESTRICT,
  position INTEGER NOT NULL CHECK (position > 0),
  PRIMARY KEY (template_version_id, section_version_id),
  UNIQUE (template_version_id, position)
);

CREATE TABLE IF NOT EXISTS consultation_form_service_mappings (
  service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
  template_version_id BIGINT NOT NULL REFERENCES consultation_form_template_versions(id) ON DELETE RESTRICT,
  required BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (service_id, template_version_id)
);

CREATE TABLE IF NOT EXISTS consultation_form_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE RESTRICT,
  template_version_id BIGINT NOT NULL REFERENCES consultation_form_template_versions(id) ON DELETE RESTRICT,
  client_id BIGINT REFERENCES clients(id) ON DELETE RESTRICT,
  crm_v2_client_id BIGINT REFERENCES crm_v2_clients(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'not_sent'
    CHECK (status IN ('not_sent', 'sent', 'opened', 'completed', 'needs_review')),
  access_token_hash TEXT CHECK (access_token_hash IS NULL OR access_token_hash ~ '^[0-9a-f]{64}$'),
  access_expires_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  opened_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  needs_review_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT consultation_form_assignment_one_client CHECK (
    (client_id IS NOT NULL AND crm_v2_client_id IS NULL)
    OR (client_id IS NULL AND crm_v2_client_id IS NOT NULL)
  ),
  CONSTRAINT consultation_form_assignment_token_pair CHECK (
    (access_token_hash IS NULL AND access_expires_at IS NULL)
    OR (access_token_hash IS NOT NULL AND access_expires_at IS NOT NULL)
  ),
  UNIQUE (appointment_id, template_version_id)
);

CREATE INDEX IF NOT EXISTS idx_consultation_form_assignments_status
  ON consultation_form_assignments(status, appointment_id);
CREATE INDEX IF NOT EXISTS idx_consultation_form_assignments_client
  ON consultation_form_assignments(client_id) WHERE client_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_consultation_form_assignments_crm_v2_client
  ON consultation_form_assignments(crm_v2_client_id) WHERE crm_v2_client_id IS NOT NULL;

-- Practitioner notes are intentionally separate from the client questionnaire.
-- The client form surface must never read this table.
CREATE TABLE IF NOT EXISTS consultation_form_practitioner_notes (
  assignment_id BIGINT PRIMARY KEY REFERENCES consultation_form_assignments(id) ON DELETE RESTRICT,
  note TEXT NOT NULL CHECK (CHAR_LENGTH(note) <= 10000),
  author_admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Reusable section library. The source labels retain provenance to the two
-- uploaded paper forms while the field model is mobile-first and composable.
INSERT INTO consultation_form_sections(section_key, title)
VALUES
  ('core_massage_consultation', 'Core Massage Consultation'),
  ('swedish_massage_screening', 'Swedish Massage Screening'),
  ('hot_stone_massage_screening', 'Hot Stone Massage Screening')
ON CONFLICT (section_key) DO NOTHING;

INSERT INTO consultation_form_section_versions(section_id, version_number, definition, source_label)
SELECT s.id, 1, $json$
{
  "schema_version": 1,
  "groups": [
    {
      "key": "client_details",
      "title": "Your details",
      "fields": [
        {"key":"first_name","type":"prefill_text","label":"First name","required":true},
        {"key":"surname","type":"prefill_text","label":"Surname","required":true},
        {"key":"mobile","type":"prefill_text","label":"Contact number","required":true},
        {"key":"email","type":"prefill_text","label":"Email address","required":false},
        {"key":"date_of_birth","type":"prefill_date","label":"Date of birth","required":false},
        {"key":"emergency_contact","type":"text","label":"Emergency contact","required":false},
        {"key":"gender","type":"prefill_text","label":"Gender","required":false},
        {"key":"id_number","type":"text","label":"ID number","required":false}
      ]
    },
    {
      "key": "health_safety",
      "title": "Health & safety",
      "questions": [
        {"key":"heart_or_high_blood_pressure","type":"yes_no","label":"Do you have a heart condition, heart disease or high blood pressure?","required":true,"follow_up":{"key":"heart_or_blood_pressure_details","type":"text","label":"Please tell us whether it is treated or untreated and share any relevant details."}},
        {"key":"diabetes","type":"yes_no","label":"Do you have diabetes?","required":true,"follow_up":{"key":"diabetes_medication","type":"text","label":"If yes, please list any medication you take for diabetes."}},
        {"key":"cancer_or_tumours","type":"yes_no","label":"Do you have cancer or cancerous tumours?","required":true},
        {"key":"radiotherapy_or_chemotherapy","type":"yes_no","label":"Are any areas currently receiving radiotherapy or chemotherapy?","required":true},
        {"key":"respiratory_disorder","type":"yes_no","label":"Do you have a respiratory disorder or condition?","required":true},
        {"key":"muscular_skeletal_disorder","type":"yes_no","label":"Do you have a muscular or skeletal disorder or condition?","required":true},
        {"key":"epilepsy","type":"yes_no","label":"Do you have epilepsy?","required":true},
        {"key":"recent_surgery","type":"yes_no","label":"Have you had recent surgery or an operation?","required":true,"follow_up":{"key":"recent_surgery_details","type":"text","label":"If yes, please give details."}},
        {"key":"pregnant","type":"yes_no","label":"Are you pregnant?","required":true},
        {"key":"headaches_migraines","type":"yes_no","label":"Do you suffer from headaches or migraines?","required":true},
        {"key":"antiretroviral_medication","type":"yes_no","label":"Are you taking anti-retroviral medication?","required":true},
        {"key":"alcohol_or_drugs","type":"yes_no","label":"Are you currently under the influence of alcohol or drugs?","required":true},
        {"key":"allergies","type":"yes_no","label":"Do you have any allergies, including aromatherapy allergies?","required":true,"follow_up":{"key":"allergy_details","type":"text","label":"If yes, please list your allergies."}}
      ]
    },
    {
      "key": "medication_and_goal",
      "title": "Medication & treatment goal",
      "fields": [
        {"key":"other_medical_conditions_or_medication","type":"textarea","label":"Do you have any other medical conditions or take chronic medication? If yes, please list the medication and what it is used for.","required":false},
        {"key":"treatment_goal","type":"textarea","label":"What would you like to achieve from the treatment?","required":false}
      ]
    }
  ]
}
$json$::jsonb,
'CLIENT CONSULTATION FORM- SWEDISH MASSAGE.pdf + Hot Stone Massage - Consultation Form.pdf'
FROM consultation_form_sections s
WHERE s.section_key='core_massage_consultation'
ON CONFLICT (section_id, version_number) DO NOTHING;

INSERT INTO consultation_form_section_versions(section_id, version_number, definition, source_label)
SELECT s.id, 1, $json$
{
  "schema_version": 1,
  "groups": [
    {
      "key": "swedish_specific",
      "title": "Swedish Massage questions",
      "questions": [
        {"key":"recent_stroke_one_year","type":"yes_no","label":"Have you had a recent stroke within the last year?","required":true},
        {"key":"kidney_disease","type":"yes_no","label":"Do you have kidney disease or a kidney disorder?","required":true},
        {"key":"skin_condition","type":"yes_no","label":"Do you have a skin disease, disorder or condition?","required":true},
        {"key":"digestive_condition","type":"yes_no","label":"Do you have a digestive disorder or condition?","required":true}
      ]
    }
  ]
}
$json$::jsonb,
'CLIENT CONSULTATION FORM- SWEDISH MASSAGE.pdf'
FROM consultation_form_sections s
WHERE s.section_key='swedish_massage_screening'
ON CONFLICT (section_id, version_number) DO NOTHING;

INSERT INTO consultation_form_section_versions(section_id, version_number, definition, source_label)
SELECT s.id, 1, $json$
{
  "schema_version": 1,
  "groups": [
    {
      "key": "hot_stone_details",
      "title": "Hot Stone Massage questions",
      "fields": [
        {"key":"doctor_name","type":"text","label":"Doctor name","required":false},
        {"key":"doctor_number","type":"text","label":"Doctor number","required":false}
      ],
      "questions": [
        {"key":"recent_stroke_six_months_to_two_years","type":"yes_no","label":"Have you had a recent stroke within the last 6 months to 2 years?","required":true},
        {"key":"nervous_disease_disorder","type":"yes_no","label":"Do you have a nervous disease or disorder?","required":true},
        {"key":"headache_frequency","type":"text","label":"If you suffer from headaches or migraines, how frequently do they occur?","required":false},
        {"key":"kidney_or_liver_disorder","type":"yes_no","label":"Do you have kidney or liver disease or a related disorder?","required":true},
        {"key":"anticoagulants_blood_thinners","type":"yes_no","label":"Are you taking anticoagulants or blood thinners?","required":true},
        {"key":"hair_loss_growth_issues","type":"yes_no","label":"Do you have hair loss or hair growth issues?","required":true}
      ]
    }
  ]
}
$json$::jsonb,
'Hot Stone Massage - Consultation Form.pdf'
FROM consultation_form_sections s
WHERE s.section_key='hot_stone_massage_screening'
ON CONFLICT (section_id, version_number) DO NOTHING;

INSERT INTO consultation_form_templates(template_key, title)
VALUES
  ('swedish_massage_consultation', 'Swedish Massage Consultation'),
  ('hot_stone_massage_consultation', 'Hot Stone Massage Consultation')
ON CONFLICT (template_key) DO NOTHING;

INSERT INTO consultation_form_template_versions(template_id, version_number, consent_text, settings)
SELECT t.id, 1,
       'I understand that the information I have given is strictly confidential between the therapist and me. All information I have given is correct and I have not left out any information. I accept that the practitioner cannot be held liable for injury, illness or death based on the nature of the treatment. I have chosen to receive this treatment out of my own free will. I acknowledge that this is a non-sexual service and that sexual advances will not be tolerated, and that the treatment may be stopped if this is breached at any time and the fee will still be payable. I acknowledge that the treatment is not a substitute for medical intervention or treatment and that no results are 100% guaranteed.',
       '{"signature_required":true,"signed_name_required":true,"signed_date_required":true}'::jsonb
FROM consultation_form_templates t
WHERE t.template_key IN ('swedish_massage_consultation','hot_stone_massage_consultation')
ON CONFLICT (template_id, version_number) DO NOTHING;

-- Compose the two client-facing forms from immutable section versions.
INSERT INTO consultation_form_template_sections(template_version_id, section_version_id, position)
SELECT tv.id, sv.id, x.position
FROM consultation_form_template_versions tv
JOIN consultation_form_templates t ON t.id=tv.template_id
JOIN LATERAL (
  VALUES
    ('core_massage_consultation'::text, 1),
    ('swedish_massage_screening'::text, 2)
) AS x(section_key, position) ON t.template_key='swedish_massage_consultation'
JOIN consultation_form_sections s ON s.section_key=x.section_key
JOIN consultation_form_section_versions sv ON sv.section_id=s.id AND sv.version_number=1
WHERE tv.version_number=1
ON CONFLICT (template_version_id, section_version_id) DO NOTHING;

INSERT INTO consultation_form_template_sections(template_version_id, section_version_id, position)
SELECT tv.id, sv.id, x.position
FROM consultation_form_template_versions tv
JOIN consultation_form_templates t ON t.id=tv.template_id
JOIN LATERAL (
  VALUES
    ('core_massage_consultation'::text, 1),
    ('hot_stone_massage_screening'::text, 2)
) AS x(section_key, position) ON t.template_key='hot_stone_massage_consultation'
JOIN consultation_form_sections s ON s.section_key=x.section_key
JOIN consultation_form_section_versions sv ON sv.section_id=s.id AND sv.version_number=1
WHERE tv.version_number=1
ON CONFLICT (template_version_id, section_version_id) DO NOTHING;

-- Resolve service names exactly once during the controlled migration, then persist
-- canonical service IDs. Runtime form selection never matches free-text treatment names.
DO $forms$
DECLARE
  v_swedish_service_id BIGINT;
  v_hot_stone_service_id BIGINT;
  v_swedish_template_version_id BIGINT;
  v_hot_stone_template_version_id BIGINT;
BEGIN
  SELECT id INTO STRICT v_swedish_service_id
    FROM services
   WHERE status='active' AND name='Full Body Swedish';

  SELECT id INTO STRICT v_hot_stone_service_id
    FROM services
   WHERE status='active' AND name='Hot Stone Massage';

  SELECT tv.id INTO STRICT v_swedish_template_version_id
    FROM consultation_form_template_versions tv
    JOIN consultation_form_templates t ON t.id=tv.template_id
   WHERE t.template_key='swedish_massage_consultation' AND tv.version_number=1;

  SELECT tv.id INTO STRICT v_hot_stone_template_version_id
    FROM consultation_form_template_versions tv
    JOIN consultation_form_templates t ON t.id=tv.template_id
   WHERE t.template_key='hot_stone_massage_consultation' AND tv.version_number=1;

  INSERT INTO consultation_form_service_mappings(service_id, template_version_id, required)
  VALUES
    (v_swedish_service_id, v_swedish_template_version_id, TRUE),
    (v_hot_stone_service_id, v_hot_stone_template_version_id, TRUE)
  ON CONFLICT (service_id, template_version_id) DO NOTHING;
END
$forms$;

-- Narrow initial Workspace access: senior clinic principals and the shared
-- Reception operator may view the Forms control centre. Practitioner-scoped
-- access to client submissions will be introduced with the secure client form
-- surface so health information is not broadened before that boundary exists.
UPDATE staff_admin_accounts
   SET permissions = COALESCE(permissions, '{}'::jsonb) || '{"forms:view":true}'::jsonb,
       updated_at = NOW()
 WHERE active=TRUE
   AND business_role IN ('owner','business_admin','booking_operator')
   AND COALESCE((permissions ->> 'forms:view')::boolean, FALSE) IS NOT TRUE;
