-- Secure client consultation form submissions.
--
-- Client health answers and the typed electronic signature are stored only as
-- application-encrypted ciphertext. The immutable questionnaire wording and
-- consent that were presented at submission time are snapshotted separately so
-- Shiloh can always prove which form version the client completed.
--
-- This migration does not issue links, send WhatsApp messages, backfill answers,
-- or enable the public client form surface by itself.

ALTER TABLE consultation_form_assignments
  ADD COLUMN IF NOT EXISTS access_issued_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS access_revoked_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS uq_consultation_form_assignments_access_token_hash
  ON consultation_form_assignments(access_token_hash)
  WHERE access_token_hash IS NOT NULL;

CREATE TABLE IF NOT EXISTS consultation_form_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT NOT NULL UNIQUE
    REFERENCES consultation_form_assignments(id) ON DELETE RESTRICT,
  template_version_id BIGINT NOT NULL
    REFERENCES consultation_form_template_versions(id) ON DELETE RESTRICT,
  payload_schema_version INTEGER NOT NULL DEFAULT 1
    CHECK (payload_schema_version = 1),
  payload_ciphertext TEXT NOT NULL
    CHECK (CHAR_LENGTH(payload_ciphertext) BETWEEN 1 AND 131072),
  payload_iv TEXT NOT NULL
    CHECK (payload_iv ~ '^[A-Za-z0-9_-]{16}$'),
  payload_auth_tag TEXT NOT NULL
    CHECK (payload_auth_tag ~ '^[A-Za-z0-9_-]{22}$'),
  template_snapshot JSONB NOT NULL
    CHECK (jsonb_typeof(template_snapshot) = 'object'),
  consent_text_snapshot TEXT NOT NULL
    CHECK (BTRIM(consent_text_snapshot) <> ''),
  signature_method TEXT NOT NULL DEFAULT 'typed_name'
    CHECK (signature_method = 'typed_name'),
  signed_at TIMESTAMPTZ NOT NULL,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_consultation_form_submissions_template_version
  ON consultation_form_submissions(template_version_id, submitted_at DESC);

COMMENT ON TABLE consultation_form_submissions IS
  'Completed consultation forms. Health answers and typed signature identity are AES-256-GCM encrypted by the application; questionnaire and consent snapshots contain no client answers.';

COMMENT ON COLUMN consultation_form_submissions.payload_ciphertext IS
  'Base64url AES-256-GCM ciphertext containing normalized client answers and the typed electronic signature name.';

COMMENT ON COLUMN consultation_form_submissions.template_snapshot IS
  'Questionnaire structure shown to the client at submission time. Contains form wording only, not client answers.';
