-- Expanded Shiloh consultation-form library from clinic source forms.
--
-- Adds Bamboo Sports Massage, Balinese Scalp Massage, Manual Lymphatic Drainage,
-- Reflexology, Back Care Clinic and Remedial / Sports Massage consultation forms.
-- Client-facing questions stay versioned and immutable. Practitioner-only remedial
-- assessment/treatment data has a separate encrypted record envelope and is never
-- part of the public client questionnaire.

CREATE TABLE IF NOT EXISTS consultation_form_practitioner_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT NOT NULL REFERENCES consultation_form_assignments(id) ON DELETE RESTRICT,
  record_type TEXT NOT NULL CHECK (BTRIM(record_type) <> ''),
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  payload_ciphertext TEXT NOT NULL CHECK (CHAR_LENGTH(payload_ciphertext) BETWEEN 1 AND 262144),
  payload_iv TEXT NOT NULL CHECK (payload_iv ~ '^[A-Za-z0-9_-]{16}$'),
  payload_auth_tag TEXT NOT NULL CHECK (payload_auth_tag ~ '^[A-Za-z0-9_-]{22}$'),
  author_admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE RESTRICT,
  finalized_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (assignment_id, record_type, schema_version)
);

COMMENT ON TABLE consultation_form_practitioner_records IS
  'Staff-only encrypted practitioner assessment/treatment records. The public consultation-form route must never read this table.';

INSERT INTO consultation_form_sections(section_key, title)
VALUES
  ('clinic_client_details_with_doctor', 'Your details'),
  ('reflexology_client_details', 'Your details'),
  ('bamboo_sports_screening', 'Bamboo Sports Massage questions'),
  ('balinese_scalp_screening', 'Balinese Scalp Massage questions'),
  ('manual_lymphatic_drainage_screening', 'Manual Lymphatic Drainage questions'),
  ('reflexology_screening', 'Reflexology questions'),
  ('back_care_clinic_screening', 'Back Care Clinic questions'),
  ('remedial_sports_screening', 'Remedial / Sports Massage questions')
ON CONFLICT (section_key) DO NOTHING;

INSERT INTO consultation_form_section_versions(section_id, version_number, definition, source_label)
SELECT s.id, 1, $json$
{
  "schema_version": 1,
  "groups": [
    {
      "key": "client_details",
      "title": "Your details",
      "fields": [
        {"key":"first_name","type":"prefill_text","label":"First name","required":true},
        {"key":"surname","type":"prefill_text","label":"Surname","required":true},
        {"key":"mobile","type":"prefill_text","label":"Cell number","required":true},
        {"key":"email","type":"prefill_text","label":"Email address","required":false},
        {"key":"date_of_birth","type":"prefill_date","label":"Date of birth","required":false},
        {"key":"emergency_contact","type":"text","label":"Emergency contact","required":false},
        {"key":"gender","type":"prefill_text","label":"Gender","required":false},
        {"key":"id_number","type":"text","label":"ID number","required":false},
        {"key":"doctor_name","type":"text","label":"Doctor name","required":false},
        {"key":"doctor_number","type":"text","label":"Doctor number","required":false}
      ]
    }
  ]
}
$json$::jsonb,
'Bamboo Sports Massage - Consultation Form.pdf + Balinese Scalp Massage - Consultation Form.pdf + MLD - Consultation Form.pdf + BACK CARE CLINIC CLIENT CONSULTATION FORM.pdf + Remedial Sports Massage - Consultation Form.pdf'
FROM consultation_form_sections s
WHERE s.section_key='clinic_client_details_with_doctor'
ON CONFLICT (section_id, version_number) DO NOTHING;

INSERT INTO consultation_form_section_versions(section_id, version_number, definition, source_label)
SELECT s.id, 1, $json$
{
  "schema_version": 1,
  "groups": [
    {
      "key": "reflexology_details",
      "title": "Your details",
      "fields": [
        {"key":"first_name","type":"prefill_text","label":"First name","required":true},
        {"key":"surname","type":"prefill_text","label":"Surname","required":true},
        {"key":"id_number","type":"text","label":"ID number","required":false},
        {"key":"mobile","type":"prefill_text","label":"Contact number","required":true},
        {"key":"doctor_name","type":"text","label":"Doctor's name","required":false},
        {"key":"doctor_number","type":"text","label":"Doctor's number","required":false},
        {"key":"alternative_contact_person","type":"text","label":"Alternative contact person","required":false},
        {"key":"alternative_contact_number","type":"text","label":"Alternative contact number","required":false}
      ]
    }
  ]
}
$json$::jsonb,
'CLIENT CONSULTATION FORM - REFLEXOLOGY.pdf'
FROM consultation_form_sections s
WHERE s.section_key='reflexology_client_details'
ON CONFLICT (section_id, version_number) DO NOTHING;

INSERT INTO consultation_form_section_versions(section_id, version_number, definition, source_label)
SELECT s.id, 1, $json$
{
  "schema_version": 1,
  "groups": [
    {
      "key": "bamboo_health",
      "title": "Health & safety",
      "questions": [
        {"key":"antiretroviral_medication","type":"yes_no","label":"Are you taking anti-retroviral medication?","required":true},
        {"key":"radiotherapy_or_chemotherapy","type":"yes_no","label":"Are any areas receiving radiotherapy or chemotherapy?","required":true},
        {"key":"cancer_or_tumours","type":"yes_no","label":"Do you have cancer or cancerous tumours?","required":true},
        {"key":"epilepsy","type":"yes_no","label":"Do you have epilepsy?","required":true},
        {"key":"diabetes","type":"yes_no","label":"Do you have diabetes Type I or II?","required":true},
        {"key":"untreated_heart_or_high_bp","type":"yes_no","label":"Do you have untreated heart disease or high blood pressure?","required":true},
        {"key":"treated_heart_or_high_bp","type":"yes_no","label":"Do you have treated heart disease or high blood pressure?","required":true},
        {"key":"recent_stroke_six_months_to_two_years","type":"yes_no","label":"Have you had a recent stroke within the last 6 months to 2 years?","required":true},
        {"key":"severe_headaches_migraines","type":"yes_no","label":"Do you suffer from severe headaches or migraines?","required":true},
        {"key":"muscular_skeletal_disorders","type":"yes_no","label":"Do you have muscular or skeletal disorders?","required":true},
        {"key":"nervous_system_disorders","type":"yes_no","label":"Do you have nervous system diseases or disorders?","required":true},
        {"key":"respiratory_disorders","type":"yes_no","label":"Do you have respiratory disorders or conditions?","required":true},
        {"key":"skin_conditions","type":"yes_no","label":"Do you have skin conditions or disorders?","required":true},
        {"key":"kidney_or_liver_disorder","type":"yes_no","label":"Do you have kidney or liver disease or disorders?","required":true},
        {"key":"digestive_disorders","type":"yes_no","label":"Do you have digestive disorders?","required":true},
        {"key":"recent_surgery","type":"yes_no","label":"Have you had recent surgery or operations?","required":true,"follow_up":{"key":"recent_surgery_details","type":"textarea","label":"If yes, please give details."}},
        {"key":"pregnant","type":"yes_no","label":"Are you pregnant?","required":true},
        {"key":"allergies","type":"yes_no","label":"Do you have allergies?","required":true,"follow_up":{"key":"allergy_details","type":"textarea","label":"If yes, please list your allergies."}},
        {"key":"alcohol_or_drugs","type":"yes_no","label":"Are you currently under the influence of alcohol or drugs?","required":true}
      ]
    },
    {
      "key": "bamboo_goal",
      "title": "Medication, focus areas & treatment goal",
      "fields": [
        {"key":"other_medical_conditions_or_medication","type":"textarea","label":"Do you have any other medical conditions or take medication? If yes, please specify.","required":false},
        {"key":"focus_areas_and_goal","type":"textarea","label":"Do you have any areas you want me to focus on, and what would you like to achieve from the treatment?","required":false}
      ]
    }
  ]
}
$json$::jsonb,
'Bamboo Sports Massage - Consultation Form.pdf'
FROM consultation_form_sections s
WHERE s.section_key='bamboo_sports_screening'
ON CONFLICT (section_id, version_number) DO NOTHING;

INSERT INTO consultation_form_section_versions(section_id, version_number, definition, source_label)
SELECT s.id, 1, $json$
{
  "schema_version": 1,
  "groups": [
    {
      "key": "balinese_health",
      "title": "Health & safety",
      "questions": [
        {"key":"antiretroviral_medication","type":"yes_no","label":"Are you taking anti-retroviral medication?","required":true},
        {"key":"radiotherapy_or_chemotherapy","type":"yes_no","label":"Are any areas receiving radiotherapy or chemotherapy?","required":true},
        {"key":"cancer_or_tumours","type":"yes_no","label":"Do you have cancer or cancerous tumours?","required":true},
        {"key":"epilepsy_or_nervous_disorder","type":"yes_no","label":"Are you epileptic or do you have a nervous disease or disorder?","required":true},
        {"key":"muscular_skeletal_disorders","type":"yes_no","label":"Do you have muscular or skeletal disorders or conditions?","required":true},
        {"key":"headaches_migraines","type":"yes_no","label":"Do you suffer from headaches or migraines?","required":true,"follow_up":{"key":"headache_frequency","type":"text","label":"If yes, how frequently?"}},
        {"key":"untreated_high_bp_or_heart_disease","type":"yes_no","label":"Do you have untreated high blood pressure or heart disease?","required":true},
        {"key":"recent_stroke_six_months_to_two_years","type":"yes_no","label":"Have you had a recent stroke within the last 6 months to 2 years?","required":true},
        {"key":"respiratory_disorders","type":"yes_no","label":"Do you have respiratory disorders or conditions?","required":true},
        {"key":"kidney_or_liver_disorder","type":"yes_no","label":"Do you have kidney or liver disease or disorders?","required":true},
        {"key":"diabetes","type":"yes_no","label":"Do you have diabetes?","required":true,"follow_up":{"key":"diabetes_medication","type":"text","label":"If yes, are you taking medication? Please give details."}},
        {"key":"anticoagulants_blood_thinners","type":"yes_no","label":"Are you taking anticoagulants or blood thinners?","required":true},
        {"key":"antidepressants","type":"yes_no","label":"Are you taking antidepressants?","required":true},
        {"key":"hair_loss_growth_issues","type":"yes_no","label":"Do you have hair loss or hair growth issues?","required":true},
        {"key":"recent_surgery","type":"yes_no","label":"Have you had recent surgery or operations?","required":true,"follow_up":{"key":"recent_surgery_details","type":"textarea","label":"If yes, please give details."}},
        {"key":"pregnant","type":"yes_no","label":"Are you pregnant?","required":true},
        {"key":"allergies","type":"yes_no","label":"Do you have allergies?","required":true,"follow_up":{"key":"allergy_details","type":"textarea","label":"If yes, please list your allergies."}},
        {"key":"alcohol_or_drugs","type":"yes_no","label":"Are you currently under the influence of alcohol or drugs?","required":true}
      ]
    },
    {
      "key": "balinese_goal",
      "title": "Medication & treatment goal",
      "fields": [
        {"key":"other_medical_conditions_or_medication","type":"textarea","label":"Do you have any other medical conditions or take medication? If yes, please specify.","required":false},
        {"key":"treatment_goal","type":"textarea","label":"What would you like to achieve from the treatment?","required":false}
      ]
    }
  ]
}
$json$::jsonb,
'Balinese Scalp Massage - Consultation Form.pdf'
FROM consultation_form_sections s
WHERE s.section_key='balinese_scalp_screening'
ON CONFLICT (section_id, version_number) DO NOTHING;

INSERT INTO consultation_form_section_versions(section_id, version_number, definition, source_label)
SELECT s.id, 1, $json$
{
  "schema_version": 1,
  "groups": [
    {
      "key": "mld_health",
      "title": "Health & safety",
      "questions": [
        {"key":"antiretroviral_medication","type":"yes_no","label":"Are you taking anti-retroviral medication?","required":true,"follow_up":{"key":"antiretroviral_condition","type":"text","label":"If yes, for what condition?"}},
        {"key":"radiotherapy_or_chemotherapy","type":"yes_no","label":"Are any areas receiving radiotherapy or chemotherapy?","required":true},
        {"key":"cancer_lymphoma_malignant_tumours","type":"yes_no","label":"Do you have cancer, lymphoma, or cancerous/malignant tumours?","required":true},
        {"key":"epilepsy_or_nervous_disorder","type":"yes_no","label":"Are you epileptic or do you have a nervous disease or disorder?","required":true},
        {"key":"cancer_remission","type":"yes_no","label":"Are you in remission from cancer?","required":true,"follow_up":{"key":"cancer_remission_type","type":"text","label":"If yes, what type of cancer?"}},
        {"key":"mastectomy","type":"yes_no","label":"Have you had a mastectomy?","required":true},
        {"key":"heart_or_high_blood_pressure","type":"yes_no","label":"Do you have treated or untreated heart disease or high blood pressure?","required":true},
        {"key":"beta_blockers_anticoagulants_blood_thinners","type":"yes_no","label":"Are you taking beta-blockers, anticoagulants or blood thinners?","required":true,"follow_up":{"key":"blood_medication_details","type":"text","label":"If yes, please give details."}},
        {"key":"thrombosis_dvt","type":"yes_no","label":"Do you have thrombosis or DVT?","required":true},
        {"key":"recent_stroke_or_heart_attack","type":"yes_no","label":"Have you had a recent stroke or heart attack within the last 6 months to 2 years?","required":true},
        {"key":"diabetes_with_complications","type":"yes_no","label":"Do you have diabetes with complications, for example gangrene?","required":true},
        {"key":"diabetes","type":"yes_no","label":"Do you have diabetes Type I or II?","required":true},
        {"key":"severe_headaches_migraines","type":"yes_no","label":"Do you suffer from severe headaches or migraines?","required":true},
        {"key":"autoimmune_disease","type":"yes_no","label":"Do you have an autoimmune disease, for example hypothyroidism or HIV?","required":true},
        {"key":"kidney_or_liver_disorder","type":"yes_no","label":"Do you have kidney or liver disease or disorders?","required":true},
        {"key":"pregnant_or_lactating","type":"yes_no","label":"Are you pregnant or lactating?","required":true},
        {"key":"recent_surgery","type":"yes_no","label":"Have you had recent surgery or operations?","required":true,"follow_up":{"key":"recent_surgery_details","type":"textarea","label":"If yes, where and when?"}},
        {"key":"lymph_nodes_removed","type":"yes_no","label":"Have you had lymph nodes removed?","required":true,"follow_up":{"key":"lymph_nodes_removed_details","type":"text","label":"If yes, please give details."}},
        {"key":"lymphedema","type":"yes_no","label":"Do you have lymphedema?","required":true,"follow_up":{"key":"lymphedema_stage","type":"text","label":"If yes, what stage?"}},
        {"key":"lipedema","type":"yes_no","label":"Do you have lipedema?","required":true,"follow_up":{"key":"lipedema_stage","type":"text","label":"If yes, what stage?"}},
        {"key":"fluid_retention","type":"yes_no","label":"Do you have fluid retention?","required":true,"follow_up":{"key":"fluid_retention_area","type":"text","label":"If yes, in which area?"}}
      ]
    },
    {
      "key": "mld_goal",
      "title": "Medication & treatment goal",
      "fields": [
        {"key":"other_medical_conditions_or_medication","type":"textarea","label":"Do you have any other medical conditions or take medication? If yes, please specify.","required":false},
        {"key":"treatment_goal","type":"textarea","label":"What would you like to achieve from the treatment?","required":false}
      ]
    }
  ]
}
$json$::jsonb,
'MLD - Consultation Form.pdf'
FROM consultation_form_sections s
WHERE s.section_key='manual_lymphatic_drainage_screening'
ON CONFLICT (section_id, version_number) DO NOTHING;

INSERT INTO consultation_form_section_versions(section_id, version_number, definition, source_label)
SELECT s.id, 1, $json$
{
  "schema_version": 1,
  "groups": [
    {
      "key": "reflexology_health",
      "title": "Health & safety",
      "questions": [
        {"key":"autoimmune_immunocompromised_endocrine","type":"yes_no","label":"Do you have auto-immune, immunocompromised or endocrine disorders?","required":true},
        {"key":"thyroid_disorder","type":"yes_no","label":"Do you have hypothyroidism or hyperthyroidism?","required":true},
        {"key":"diabetes","type":"yes_no","label":"Do you have diabetes mellitus, Type 1 or Type 2?","required":true},
        {"key":"cancer_or_tumours","type":"yes_no","label":"Do you have cancer or cancerous tumours?","required":true},
        {"key":"radiotherapy_or_chemotherapy","type":"yes_no","label":"Are any areas receiving chemotherapy or radiotherapy?","required":true},
        {"key":"hiv_aids","type":"yes_no","label":"Do you have HIV/AIDS?","required":true},
        {"key":"antiretroviral_medication","type":"yes_no","label":"Are you taking ARV medication?","required":true},
        {"key":"chronic_fatigue_adrenal_fatigue_burnout","type":"yes_no","label":"Do you have Chronic Fatigue Syndrome, adrenal fatigue or burnout?","required":true},
        {"key":"organ_transplant","type":"yes_no","label":"Have you had an organ transplant?","required":true},
        {"key":"recent_surgery","type":"yes_no","label":"Have you had recent surgery or operations?","required":true,"follow_up":{"key":"recent_surgery_details","type":"textarea","label":"If yes, where, for what, and how long ago?"}},
        {"key":"liver_disorder","type":"yes_no","label":"Do you have liver disease or disorders not mentioned elsewhere?","required":true},
        {"key":"gallstones","type":"yes_no","label":"Do you have gallstones?","required":true},
        {"key":"kidney_urinary_disorder","type":"yes_no","label":"Do you have kidney or urinary disorders or conditions not mentioned below?","required":true},
        {"key":"kidney_stones","type":"yes_no","label":"Do you have kidney stones?","required":true},
        {"key":"bladder_infection","type":"yes_no","label":"Do you have a bladder infection?","required":true},
        {"key":"eye_ear_disorder","type":"yes_no","label":"Do you have eye or ear disorders or conditions not mentioned below?","required":true},
        {"key":"eye_conditions","type":"yes_no","label":"Do you have eye problems or conditions such as blindness or glaucoma?","required":true},
        {"key":"ear_conditions","type":"yes_no","label":"Do you have ear-related conditions such as tinnitus or middle ear infection?","required":true},
        {"key":"reproductive_disorder","type":"yes_no","label":"Do you have reproductive problems or disorders not mentioned below?","required":true},
        {"key":"endometriosis_or_cystitis","type":"yes_no","label":"Do you have endometriosis or cystitis?","required":true},
        {"key":"infertility","type":"yes_no","label":"Do you experience infertility?","required":true},
        {"key":"menstruation_disorders","type":"yes_no","label":"Do you have menstruation-related disorders or imbalances?","required":true},
        {"key":"prostate_disorders","type":"yes_no","label":"Do you have prostate disorders such as prostatitis?","required":true},
        {"key":"pregnant","type":"yes_no","label":"Are you pregnant?","required":true,"follow_up":{"key":"pregnancy_months","type":"text","label":"If yes, how many months?"}},
        {"key":"lymph_disorders","type":"yes_no","label":"Do you have lymph-related disorders or conditions not mentioned below?","required":true},
        {"key":"lymphedema_lipedema_oedema_fluid_retention","type":"yes_no","label":"Do you have lymphedema, lipedema, oedema or fluid retention?","required":true},
        {"key":"skin_conditions","type":"yes_no","label":"Do you have skin conditions or disorders not mentioned below?","required":true},
        {"key":"eczema_psoriasis_acne","type":"yes_no","label":"Do you have eczema, psoriasis or acne?","required":true},
        {"key":"digestive_disorders","type":"yes_no","label":"Do you have digestive disorders or imbalances not mentioned below?","required":true},
        {"key":"constipation","type":"yes_no","label":"Do you experience constipation?","required":true},
        {"key":"diarrhoea","type":"yes_no","label":"Do you experience diarrhoea?","required":true},
        {"key":"ibs","type":"yes_no","label":"Do you have IBS?","required":true},
        {"key":"diverticulitis_or_crohns","type":"yes_no","label":"Do you have diverticulitis or Crohn's disease?","required":true},
        {"key":"nervous_musculoskeletal_disorder","type":"yes_no","label":"Do you have nervous system or musculoskeletal disease or disorders not mentioned below?","required":true},
        {"key":"epilepsy","type":"yes_no","label":"Do you have epilepsy?","required":true},
        {"key":"parkinsons","type":"yes_no","label":"Do you have Parkinson disease?","required":true},
        {"key":"multiple_sclerosis","type":"yes_no","label":"Do you have MS / multiple sclerosis?","required":true},
        {"key":"headaches_migraines","type":"yes_no","label":"Do you suffer from headaches or migraines?","required":true},
        {"key":"neuralgia","type":"yes_no","label":"Do you have neuralgia?","required":true},
        {"key":"fibromyalgia","type":"yes_no","label":"Do you have fibromyalgia?","required":true},
        {"key":"muscular_aches_pains_inflammation_tension","type":"yes_no","label":"Do you have muscular aches, pains, inflammation or tension?","required":true},
        {"key":"depression_anxiety","type":"yes_no","label":"Do you experience depression or anxiety?","required":true},
        {"key":"bipolar_adhd_add","type":"yes_no","label":"Do you have bipolar disorder, ADHD or ADD?","required":true},
        {"key":"scoliosis","type":"yes_no","label":"Do you have scoliosis?","required":true},
        {"key":"osteoporosis","type":"yes_no","label":"Do you have osteoporosis?","required":true},
        {"key":"rheumatism_arthritis","type":"yes_no","label":"Do you have rheumatism or arthritis?","required":true},
        {"key":"cardiovascular_respiratory_disorder","type":"yes_no","label":"Do you have cardiovascular or respiratory diseases or disorders not mentioned below?","required":true},
        {"key":"heart_disease","type":"yes_no","label":"Do you have treated or untreated heart disease?","required":true},
        {"key":"recent_stroke_heart_attack","type":"yes_no","label":"Have you had a recent stroke or heart attack within the last 6 months to 2 years?","required":true},
        {"key":"high_blood_pressure","type":"yes_no","label":"Do you have treated or untreated high blood pressure?","required":true},
        {"key":"respiratory_conditions","type":"yes_no","label":"Do you have respiratory conditions not mentioned below?","required":true},
        {"key":"asthma","type":"yes_no","label":"Do you have asthma?","required":true},
        {"key":"emphysema","type":"yes_no","label":"Do you have emphysema?","required":true},
        {"key":"acute_inflammatory_bronchitis","type":"yes_no","label":"Do you have an acute inflammatory condition such as bronchitis?","required":true},
        {"key":"alcohol_or_drugs","type":"yes_no","label":"Are you currently under the influence of drugs or alcohol?","required":true},
        {"key":"previous_reflexology","type":"yes_no","label":"Have you ever received a Reflexology treatment?","required":true}
      ]
    },
    {
      "key": "reflexology_goal",
      "title": "Medication, focus areas & treatment goal",
      "fields": [
        {"key":"other_medical_conditions_or_medication","type":"textarea","label":"Do you have any other medical conditions? If so, what medication are you taking?","required":false},
        {"key":"health_focus_or_pain","type":"textarea","label":"Are there any specific areas of health you would like me to focus on, or areas experiencing pain or discomfort?","required":false},
        {"key":"treatment_goal","type":"textarea","label":"What would you like to achieve from this treatment? Please note urgency and whether concerns are acute or chronic.","required":false}
      ]
    }
  ]
}
$json$::jsonb,
'CLIENT CONSULTATION FORM - REFLEXOLOGY.pdf'
FROM consultation_form_sections s
WHERE s.section_key='reflexology_screening'
ON CONFLICT (section_id, version_number) DO NOTHING;

INSERT INTO consultation_form_section_versions(section_id, version_number, definition, source_label)
SELECT s.id, 1, $json$
{
  "schema_version": 1,
  "groups": [
    {
      "key": "back_care_health",
      "title": "Health & safety",
      "questions": [
        {"key":"antiretroviral_medication","type":"yes_no","label":"Are you taking anti-retroviral medication?","required":true},
        {"key":"radiotherapy_or_chemotherapy","type":"yes_no","label":"Are any areas receiving radiotherapy or chemotherapy?","required":true},
        {"key":"cancer_or_tumours","type":"yes_no","label":"Do you have cancer or cancerous tumours?","required":true},
        {"key":"epilepsy","type":"yes_no","label":"Do you have epilepsy?","required":true},
        {"key":"diabetes","type":"yes_no","label":"Do you have diabetes Type 1 or 2?","required":true},
        {"key":"untreated_heart_or_blood_pressure","type":"yes_no","label":"Do you have untreated heart disease or blood pressure concerns?","required":true},
        {"key":"recent_stroke_six_months_to_two_years","type":"yes_no","label":"Have you had a recent stroke within the last 6 months to 2 years?","required":true},
        {"key":"severe_headaches_migraines","type":"yes_no","label":"Do you suffer from severe headaches or migraines?","required":true},
        {"key":"muscular_disorders","type":"yes_no","label":"Do you have muscular diseases or disorders?","required":true},
        {"key":"nervous_disorders","type":"yes_no","label":"Do you have nervous diseases or disorders?","required":true},
        {"key":"respiratory_disorders","type":"yes_no","label":"Do you have respiratory disorders?","required":true},
        {"key":"kidney_disorder","type":"yes_no","label":"Do you have kidney disease or disorders?","required":true},
        {"key":"skin_disorders","type":"yes_no","label":"Do you have skin diseases or disorders?","required":true},
        {"key":"recent_surgery","type":"yes_no","label":"Have you had recent surgery or operations?","required":true,"follow_up":{"key":"recent_surgery_details","type":"textarea","label":"If yes, please give details."}},
        {"key":"pregnant_or_lactating","type":"yes_no","label":"Are you pregnant or lactating?","required":true},
        {"key":"allergies","type":"yes_no","label":"Do you have allergies?","required":true,"follow_up":{"key":"allergy_details","type":"textarea","label":"If yes, please list your allergies."}},
        {"key":"alcohol_or_drugs","type":"yes_no","label":"Are you currently under the influence of alcohol or drugs?","required":true},
        {"key":"covid_vaccination","type":"yes_no","label":"Have you received a Covid vaccination?","required":true,"follow_up":{"key":"covid_vaccine_details","type":"textarea","label":"If yes, which one, how many doses, and what was the date of your last shot?"}},
        {"key":"covid_vaccine_symptoms","type":"yes_no","label":"Did you have any symptoms after the vaccination?","required":true,"follow_up":{"key":"covid_vaccine_symptom_details","type":"textarea","label":"If yes, please give details."}},
        {"key":"covid_vaccine_ongoing_symptoms","type":"yes_no","label":"Do you still show any symptoms or side effects?","required":true,"follow_up":{"key":"covid_vaccine_ongoing_details","type":"textarea","label":"If yes, please give details."}}
      ]
    },
    {
      "key": "back_care_goal",
      "title": "Medication, focus areas & treatment goal",
      "fields": [
        {"key":"other_medical_conditions_or_medication","type":"textarea","label":"Do you have any other medical conditions or take medication? If yes, please specify.","required":false},
        {"key":"focus_areas_and_goal","type":"textarea","label":"What would you like me to focus on, and what would you like to achieve from this session?","required":false}
      ]
    }
  ]
}
$json$::jsonb,
'BACK CARE CLINIC CLIENT CONSULTATION FORM.pdf'
FROM consultation_form_sections s
WHERE s.section_key='back_care_clinic_screening'
ON CONFLICT (section_id, version_number) DO NOTHING;

INSERT INTO consultation_form_section_versions(section_id, version_number, definition, source_label)
SELECT s.id, 1, $json$
{
  "schema_version": 1,
  "groups": [
    {
      "key": "remedial_health",
      "title": "Health & safety",
      "questions": [
        {"key":"antiretroviral_medication","type":"yes_no","label":"Are you taking anti-retroviral medication?","required":true},
        {"key":"radiotherapy_or_chemotherapy","type":"yes_no","label":"Are any areas receiving radiotherapy or chemotherapy?","required":true},
        {"key":"cancer_or_tumours","type":"yes_no","label":"Do you have cancer or cancerous tumours?","required":true},
        {"key":"epilepsy","type":"yes_no","label":"Do you have epilepsy?","required":true},
        {"key":"diabetes","type":"yes_no","label":"Do you have diabetes Type I or Type II?","required":true},
        {"key":"untreated_heart_or_high_bp","type":"yes_no","label":"Do you have untreated heart disease or untreated high blood pressure?","required":true},
        {"key":"treated_heart_or_high_bp","type":"yes_no","label":"Do you have treated heart disease or treated high blood pressure?","required":true},
        {"key":"recent_stroke_six_months_to_two_years","type":"yes_no","label":"Have you had a recent stroke within the last 6 months to 2 years?","required":true},
        {"key":"severe_headaches_migraines","type":"yes_no","label":"Do you suffer from severe headaches or migraines?","required":true},
        {"key":"autoimmune_disorders","type":"yes_no","label":"Do you have an auto-immune disease or disorder?","required":true},
        {"key":"nervous_muscular_disorders","type":"yes_no","label":"Do you have nervous or muscular diseases or disorders?","required":true},
        {"key":"respiratory_disorders","type":"yes_no","label":"Do you have respiratory disorders?","required":true},
        {"key":"kidney_or_liver_disorder","type":"yes_no","label":"Do you have kidney or liver disease or disorders?","required":true},
        {"key":"skin_disorders","type":"yes_no","label":"Do you have skin diseases or disorders?","required":true},
        {"key":"recent_surgery","type":"yes_no","label":"Have you had recent surgery or operations?","required":true,"follow_up":{"key":"recent_surgery_details","type":"textarea","label":"If yes, please give details."}},
        {"key":"pregnant","type":"yes_no","label":"Are you pregnant?","required":true},
        {"key":"allergies","type":"yes_no","label":"Do you have allergies?","required":true,"follow_up":{"key":"allergy_details","type":"textarea","label":"If yes, please list your allergies."}},
        {"key":"alcohol_or_drugs","type":"yes_no","label":"Are you currently under the influence of alcohol or drugs?","required":true}
      ]
    },
    {
      "key": "remedial_history_goal",
      "title": "Your activity, concerns & treatment goal",
      "fields": [
        {"key":"other_medical_conditions_or_medication","type":"textarea","label":"Are there any other medical conditions or medications? If yes, please specify.","required":false},
        {"key":"occupation_physical_stresses","type":"textarea","label":"Occupation: what physical stresses are involved, for example sitting or driving?","required":false},
        {"key":"sporting_activities_or_previous_injuries","type":"textarea","label":"Please tell us about your sporting activities or previous sports injuries.","required":false},
        {"key":"pain_or_concern_areas","type":"textarea","label":"Where are you currently experiencing pain or concern?","required":false},
        {"key":"pain_concern_description","type":"textarea","label":"Please describe the pain or concern in your own words.","required":false},
        {"key":"treatment_goal","type":"textarea","label":"What are your goals for the treatment?","required":false}
      ]
    }
  ]
}
$json$::jsonb,
'Remedial Sports Massage - Consultation Form.pdf'
FROM consultation_form_sections s
WHERE s.section_key='remedial_sports_screening'
ON CONFLICT (section_id, version_number) DO NOTHING;

INSERT INTO consultation_form_templates(template_key, title)
VALUES
  ('bamboo_sports_massage_consultation', 'Bamboo Sports Massage Consultation'),
  ('balinese_scalp_massage_consultation', 'Balinese Scalp Massage Consultation'),
  ('manual_lymphatic_drainage_consultation', 'Manual Lymphatic Drainage Consultation'),
  ('reflexology_consultation', 'Reflexology Consultation'),
  ('back_care_clinic_consultation', 'Back Care Clinic Consultation'),
  ('remedial_sports_massage_consultation', 'Remedial / Sports Massage Consultation')
ON CONFLICT (template_key) DO NOTHING;

WITH source(template_key, consent_text, settings) AS (
  VALUES
    ('bamboo_sports_massage_consultation',
     'I understand that this information that I have given is strictly confidential between the therapist and me. All the information that I have given is correct and I have not left out any information. I accept that the practitioner cannot be held liable for any for injury, illness or death based on the nature of the treatment. I have chosen to receive this treatment out of my own free will. I acknowledge that this is a non-sexual service and that sexual advances will not be tolerated and that the treatment may be stopped if this is breached at any time and the fee will still be payable. I acknowledge that the treatment is not a substitute for medical intervention or treatment and that no results are 100% guaranteed (as like in all forms of medicine or treatment).',
     '{"signature_required":true,"signed_name_required":true,"signed_date_required":true}'::jsonb),
    ('balinese_scalp_massage_consultation',
     'I understand that this information that I have given is strictly confidential between the therapist and me. All the information that I have given is correct and I have not left out any information. I accept that the practitioner cannot be held liable for any for injury, illness or death based on the nature of the treatment. I have chosen to receive this treatment out of my own free will. I acknowledge that this is a non-sexual service and that sexual advances will not be tolerated, and that the treatment may be stopped if this is breached at any time and the fee will still be payable. I acknowledge that the treatment is not a substitute for medical intervention or treatment and that no results are 100% guaranteed (as like in all forms of medicine or treatment).',
     '{"signature_required":true,"signed_name_required":true,"signed_date_required":true}'::jsonb),
    ('manual_lymphatic_drainage_consultation',
     'I understand that this information that I have given is strictly confidential between the therapist and me. All the information that I have given is correct and I have not left out any information. I accept that the practitioner cannot be held liable for any for injury, illness or death based on the nature of the treatment. I have chosen to receive this treatment out of my own free will. I acknowledge that this is a non-sexual service and that sexual advances will not be tolerated, and that the treatment may be stopped if this is breached at any time and the fee will still be payable. I acknowledge that the treatment is not a substitute for medical intervention or treatment and that no results are 100% guaranteed (as like in all forms of medicine or treatment).',
     '{"signature_required":true,"signed_name_required":true,"signed_date_required":true}'::jsonb),
    ('back_care_clinic_consultation',
     'I understand that this information that I have given is strictly confidential between the therapist and me. All the information that I have given is correct and I have not left out any information. I accept that the practitioner cannot be held liable for any for injury, illness or death based on the nature of the treatment. I have chosen to receive this treatment out of my own free will. I acknowledge that this is a non-sexual service and that sexual advances will not be tolerated and that the treatment may be stopped if this is breached at any time and the fee will still be payable. I acknowledge that the treatment is not a substitute for medical intervention or treatment and that no results are 100% guaranteed (as like in all forms of medicine or treatment).',
     '{"signature_required":true,"signed_name_required":true,"signed_date_required":true}'::jsonb),
    ('remedial_sports_massage_consultation',
     'I understand that this information that I have given is strictly confidential between the therapist and me. All the information that I have given is correct and I have not left out any information. I accept that the practitioner cannot be held liable for any for injury, illness or death based on the nature of the treatment. I have chosen to receive this treatment out of my own free will. I acknowledge that this is a non-sexual service and that sexual advances will not be tolerated, and that the treatment may be stopped if this is breached at any time and the fee will still be payable. I acknowledge that the treatment is not a substitute for medical intervention or treatment and that no results are 100% guaranteed (as like in all forms of medicine or treatment).',
     '{"signature_required":true,"signed_name_required":true,"signed_date_required":true,"practitioner_record_type":"remedial_sports_v1"}'::jsonb),
    ('reflexology_consultation',
     'I acknowledge and understand that all the information I have given is strictly confidential between me and the practitioner; that it is for my benefit; that I may gain the most out of the treatment(s), without causing any unnecessary health risks. I confirm that all the information I have provided pertaining to this form is correct and true; that I have not left out any vital information that may jeopardize the health, safety and hygiene protocols of the practice/business, or that of the Practitioner. I understand the relevance and necessity for a thorough consultation and adhere to the safety and hygiene policies and protocols set out and explained to me by the practitioner. I acknowledge that the practitioner cannot be held liable for any for injury, illness or death based on the nature of the treatment. I have chosen to receive this treatment out of my own free will. I acknowledge that the treatment is not a substitute for medical intervention or medical treatment and that no results are 100% guaranteed (as like in all forms of medicine.) I concede to receiving touch from the signed practitioner by my choice for my body.',
     '{"signature_required":true,"signed_name_required":true,"signed_date_required":true}'::jsonb)
)
INSERT INTO consultation_form_template_versions(template_id, version_number, consent_text, settings)
SELECT t.id, 1, source.consent_text, source.settings
FROM source
JOIN consultation_form_templates t ON t.template_key=source.template_key
ON CONFLICT (template_id, version_number) DO NOTHING;

WITH composition(template_key, section_key, position) AS (
  VALUES
    ('bamboo_sports_massage_consultation','clinic_client_details_with_doctor',1),
    ('bamboo_sports_massage_consultation','bamboo_sports_screening',2),
    ('balinese_scalp_massage_consultation','clinic_client_details_with_doctor',1),
    ('balinese_scalp_massage_consultation','balinese_scalp_screening',2),
    ('manual_lymphatic_drainage_consultation','clinic_client_details_with_doctor',1),
    ('manual_lymphatic_drainage_consultation','manual_lymphatic_drainage_screening',2),
    ('reflexology_consultation','reflexology_client_details',1),
    ('reflexology_consultation','reflexology_screening',2),
    ('back_care_clinic_consultation','clinic_client_details_with_doctor',1),
    ('back_care_clinic_consultation','back_care_clinic_screening',2),
    ('remedial_sports_massage_consultation','clinic_client_details_with_doctor',1),
    ('remedial_sports_massage_consultation','remedial_sports_screening',2)
)
INSERT INTO consultation_form_template_sections(template_version_id, section_version_id, position)
SELECT tv.id, sv.id, composition.position
FROM composition
JOIN consultation_form_templates t ON t.template_key=composition.template_key
JOIN consultation_form_template_versions tv ON tv.template_id=t.id AND tv.version_number=1
JOIN consultation_form_sections s ON s.section_key=composition.section_key
JOIN consultation_form_section_versions sv ON sv.section_id=s.id AND sv.version_number=1
ON CONFLICT (template_version_id, section_version_id) DO NOTHING;

-- Only treatments with an exact canonical service identity are auto-mapped here.
-- Balinese Scalp Massage and Reflexology remain available in the Forms library but
-- deliberately unmapped until their corresponding services exist in the canonical catalogue.
DO $forms$
DECLARE
  expected_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO expected_count
    FROM services
   WHERE status='active'
     AND external_source='goldie'
     AND external_id = ANY (ARRAY[
       '6a0c9c5e-d7e7-4a82-8795-e8281a0bd526',
       '90baece3-1520-4368-b772-eaba08e1a511',
       '9f2f6452-f1ce-4525-88f2-3dc57f74caa6',
       'b5c96105-f534-406d-89ec-68e78c65cf8b',
       'b39dcaf1-7894-40e0-8a51-c7ab4eba553a',
       '46043512-d1df-4169-92b4-132160fca809',
       '2d5b6147-ee9f-4a97-8e27-6270751c2673'
     ]::TEXT[]);

  IF expected_count <> 7 THEN
    RAISE EXCEPTION 'Expanded consultation-form mapping expected 7 active canonical Goldie services; found %', expected_count;
  END IF;
END $forms$;

WITH mapping(external_id, template_key) AS (
  VALUES
    ('6a0c9c5e-d7e7-4a82-8795-e8281a0bd526','bamboo_sports_massage_consultation'),
    ('90baece3-1520-4368-b772-eaba08e1a511','manual_lymphatic_drainage_consultation'),
    ('9f2f6452-f1ce-4525-88f2-3dc57f74caa6','back_care_clinic_consultation'),
    ('b5c96105-f534-406d-89ec-68e78c65cf8b','back_care_clinic_consultation'),
    ('b39dcaf1-7894-40e0-8a51-c7ab4eba553a','back_care_clinic_consultation'),
    ('46043512-d1df-4169-92b4-132160fca809','remedial_sports_massage_consultation'),
    ('2d5b6147-ee9f-4a97-8e27-6270751c2673','remedial_sports_massage_consultation')
)
INSERT INTO consultation_form_service_mappings(service_id, template_version_id, required)
SELECT s.id, tv.id, TRUE
FROM mapping
JOIN services s ON s.external_source='goldie' AND s.external_id=mapping.external_id AND s.status='active'
JOIN consultation_form_templates t ON t.template_key=mapping.template_key
JOIN consultation_form_template_versions tv ON tv.template_id=t.id AND tv.version_number=1
ON CONFLICT (service_id, template_version_id) DO NOTHING;
