-- Shiloh gift vouchers: purchaser-owned orders, verified-payment issuance and an immutable value ledger.

CREATE TABLE IF NOT EXISTS gift_voucher_settings (
  singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
  validity_mode TEXT CHECK (validity_mode IN ('no_expiry','fixed_months')),
  validity_months INTEGER CHECK (validity_months BETWEEN 1 AND 120),
  updated_by_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT gift_voucher_settings_validity CHECK (
    validity_mode IS NULL OR
    (validity_mode = 'no_expiry' AND validity_months IS NULL) OR
    (validity_mode = 'fixed_months' AND validity_months IS NOT NULL)
  )
);
INSERT INTO gift_voucher_settings(singleton) VALUES(TRUE) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS gift_voucher_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchaser_crm_v2_client_id BIGINT NOT NULL REFERENCES crm_v2_clients(id) ON DELETE RESTRICT,
  recipient_name TEXT NOT NULL CHECK (CHAR_LENGTH(TRIM(recipient_name)) BETWEEN 1 AND 120),
  from_name TEXT NOT NULL CHECK (CHAR_LENGTH(TRIM(from_name)) BETWEEN 1 AND 120),
  personal_message TEXT CHECK (personal_message IS NULL OR CHAR_LENGTH(personal_message) <= 280),
  language TEXT NOT NULL CHECK (language IN ('en','af')),
  delivery_recipient TEXT NOT NULL CHECK (delivery_recipient IN ('purchaser','recipient')),
  delivery_mobile TEXT NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  currency CHAR(3) NOT NULL DEFAULT 'ZAR' CHECK (currency = 'ZAR'),
  validity_mode TEXT NOT NULL CHECK (validity_mode IN ('no_expiry','fixed_months')),
  validity_months INTEGER CHECK (validity_months BETWEEN 1 AND 120),
  state TEXT NOT NULL DEFAULT 'awaiting_payment' CHECK (state IN ('awaiting_payment','paid','failed','cancelled','refunded')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT gift_voucher_orders_validity CHECK (
    (validity_mode = 'no_expiry' AND validity_months IS NULL) OR
    (validity_mode = 'fixed_months' AND validity_months IS NOT NULL)
  )
);

ALTER TABLE payment_requests ALTER COLUMN payment_account_id DROP NOT NULL;
ALTER TABLE payment_requests ADD COLUMN IF NOT EXISTS gift_voucher_order_id BIGINT REFERENCES gift_voucher_orders(id) ON DELETE RESTRICT;
ALTER TABLE payment_requests DROP CONSTRAINT IF EXISTS payment_requests_one_subject;
ALTER TABLE payment_requests ADD CONSTRAINT payment_requests_one_subject CHECK (
  (payment_account_id IS NOT NULL)::integer + (gift_voucher_order_id IS NOT NULL)::integer = 1
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_requests_gift_voucher_order
  ON payment_requests(gift_voucher_order_id) WHERE gift_voucher_order_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS gift_vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL UNIQUE REFERENCES gift_voucher_orders(id) ON DELETE RESTRICT,
  voucher_code TEXT NOT NULL UNIQUE,
  original_value NUMERIC(12,2) NOT NULL CHECK (original_value > 0),
  balance NUMERIC(12,2) NOT NULL CHECK (balance >= 0 AND balance <= original_value),
  state TEXT NOT NULL DEFAULT 'active' CHECK (state IN ('active','redeemed','cancelled','refunded')),
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  valid_until DATE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS gift_voucher_ledger_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL REFERENCES gift_vouchers(id) ON DELETE RESTRICT,
  entry_type TEXT NOT NULL CHECK (entry_type IN ('issue','redemption','adjustment')),
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  operation_key TEXT NOT NULL UNIQUE,
  actor_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  notes TEXT CHECK (notes IS NULL OR CHAR_LENGTH(notes) <= 240),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gift_voucher_orders_purchaser ON gift_voucher_orders(purchaser_crm_v2_client_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gift_vouchers_state ON gift_vouchers(state, issued_at DESC);
CREATE INDEX IF NOT EXISTS idx_gift_voucher_ledger_voucher ON gift_voucher_ledger_entries(voucher_id, created_at DESC);

UPDATE staff_admin_accounts
   SET permissions = COALESCE(permissions, '{}'::jsonb) || '{"voucher:view":true,"voucher:redeem":true}'::jsonb,
       updated_at = NOW()
 WHERE active = TRUE
   AND business_role IN ('owner','booking_operator')
   AND calendar_scope = 'all_business'
   AND service_scope = 'all_services';

UPDATE staff_admin_accounts
   SET permissions = COALESCE(permissions, '{}'::jsonb) || '{"voucher:manage":true}'::jsonb,
       updated_at = NOW()
 WHERE active = TRUE
   AND business_role = 'owner'
   AND calendar_scope = 'all_business'
   AND service_scope = 'all_services';

COMMENT ON TABLE gift_voucher_ledger_entries IS
  'Immutable Shiloh voucher value evidence. Voucher issuance requires verified payment; redemption never changes booking truth.';
COMMENT ON COLUMN gift_voucher_orders.validity_mode IS
  'A snapshot of the explicit Shiloh policy selected before checkout; no default policy is invented by application code.';
