-- Shiloh Rewards: 5% Rand credit, unlocked at R100, with no expiry.
-- This is the single forward-looking loyalty authority. The legacy fifth-visit
-- tables remain untouched as historical evidence and receive no new accruals.

CREATE TABLE IF NOT EXISTS loyalty_program_settings (
  singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
  earn_basis_points INTEGER NOT NULL DEFAULT 500 CHECK (earn_basis_points BETWEEN 1 AND 10000),
  unlock_threshold NUMERIC(12,2) NOT NULL DEFAULT 100.00 CHECK (unlock_threshold > 0),
  expiry_mode TEXT NOT NULL DEFAULT 'no_expiry' CHECK (expiry_mode = 'no_expiry'),
  activated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO loyalty_program_settings(singleton,earn_basis_points,unlock_threshold,expiry_mode)
VALUES(TRUE,500,100.00,'no_expiry')
ON CONFLICT(singleton) DO NOTHING;

CREATE TABLE IF NOT EXISTS loyalty_wallets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crm_v2_client_id BIGINT NOT NULL UNIQUE REFERENCES crm_v2_clients(id) ON DELETE RESTRICT,
  currency CHAR(3) NOT NULL DEFAULT 'ZAR' CHECK (currency = 'ZAR'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS loyalty_wallet_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id BIGINT NOT NULL REFERENCES loyalty_wallets(id) ON DELETE RESTRICT,
  entry_type TEXT NOT NULL CHECK (entry_type IN ('earn','earn_reversal','redeem','redemption_reversal','adjustment')),
  signed_amount NUMERIC(12,2) NOT NULL CHECK (signed_amount <> 0),
  operation_key TEXT NOT NULL UNIQUE,
  source_payment_ledger_entry_id BIGINT UNIQUE REFERENCES payment_ledger_entries(id) ON DELETE RESTRICT,
  booking_payment_account_id BIGINT REFERENCES booking_payment_accounts(id) ON DELETE RESTRICT,
  appointment_id BIGINT REFERENCES appointments(id) ON DELETE RESTRICT,
  actor_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  notes TEXT CHECK (notes IS NULL OR CHAR_LENGTH(notes) <= 240),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT loyalty_wallet_entry_sign CHECK (
    (entry_type IN ('earn','redemption_reversal') AND signed_amount > 0) OR
    (entry_type IN ('earn_reversal','redeem') AND signed_amount < 0) OR
    entry_type = 'adjustment'
  )
);

CREATE INDEX IF NOT EXISTS idx_loyalty_wallet_entries_wallet
  ON loyalty_wallet_entries(wallet_id,created_at DESC,id DESC);

CREATE TABLE IF NOT EXISTS booking_loyalty_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_payment_account_id BIGINT NOT NULL REFERENCES booking_payment_accounts(id) ON DELETE RESTRICT,
  wallet_id BIGINT NOT NULL REFERENCES loyalty_wallets(id) ON DELETE RESTRICT,
  debit_entry_id BIGINT NOT NULL UNIQUE REFERENCES loyalty_wallet_entries(id) ON DELETE RESTRICT,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  state TEXT NOT NULL DEFAULT 'applied' CHECK (state IN ('applied','reversed')),
  applied_by_client_session_id BIGINT REFERENCES client_browser_sessions(id) ON DELETE SET NULL,
  applied_by_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  client_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  operation_key TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reversed_at TIMESTAMPTZ,
  CONSTRAINT booking_loyalty_allocation_actor CHECK (
    num_nonnulls(applied_by_client_session_id,applied_by_admin_id) = 1
  ),
  CONSTRAINT booking_loyalty_staff_confirmation CHECK (
    applied_by_admin_id IS NULL OR client_confirmed = TRUE
  )
);

CREATE INDEX IF NOT EXISTS idx_booking_loyalty_allocations_account
  ON booking_loyalty_allocations(booking_payment_account_id,state,created_at DESC);

ALTER TABLE payment_requests
  ADD COLUMN IF NOT EXISTS payer_crm_v2_client_id BIGINT REFERENCES crm_v2_clients(id) ON DELETE SET NULL;

ALTER TABLE payment_ledger_entries
  ADD COLUMN IF NOT EXISTS payer_crm_v2_client_id BIGINT REFERENCES crm_v2_clients(id) ON DELETE SET NULL;

UPDATE staff_admin_accounts
   SET permissions = COALESCE(permissions,'{}'::jsonb)
                     || '{"loyalty:view":true,"loyalty:redeem":true}'::jsonb,
       updated_at = NOW()
 WHERE active = TRUE
   AND business_role IN ('owner','booking_operator')
   AND calendar_scope = 'all_business'
   AND service_scope = 'all_services';

UPDATE staff_admin_accounts
   SET permissions = COALESCE(permissions,'{}'::jsonb)
                     || '{"loyalty:manage":true}'::jsonb,
       updated_at = NOW()
 WHERE active = TRUE
   AND business_role = 'owner'
   AND calendar_scope = 'all_business'
   AND service_scope = 'all_services';

COMMENT ON TABLE loyalty_wallet_entries IS
  'Immutable Shiloh Rewards value evidence. Balance is the sum of signed entries; rows are never rewritten.';
COMMENT ON TABLE booking_loyalty_allocations IS
  'Client-confirmed reward value applied separately from cash/Ozow payment truth.';
COMMENT ON TABLE loyalty_visits IS
  'Retired fifth-visit loyalty history. Preserved for audit; no new visits accrue after Shiloh Rewards activation.';
COMMENT ON TABLE loyalty_rewards IS
  'Retired percentage-reward history. Preserved for audit; Shiloh Rewards uses the Rand wallet authority.';
