-- A small, private problem-reporting channel for My Shiloh and Workspace.
-- Submission is available to authenticated clients and staff. Inbox management
-- is granted only to Jean-Pierre's existing canonical business-admin account.

CREATE TABLE IF NOT EXISTS problem_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_code TEXT NOT NULL UNIQUE
    CHECK (reference_code ~ '^SH-[0-9]{6}-[A-F0-9]{8}$'),
  source TEXT NOT NULL CHECK (source IN ('my_shiloh','workspace','whatsapp')),
  reporter_type TEXT NOT NULL CHECK (reporter_type IN ('client','staff')),
  reporter_staff_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE RESTRICT,
  reporter_crm_v2_client_id BIGINT REFERENCES crm_v2_clients(id) ON DELETE RESTRICT,
  reporter_name_snapshot TEXT NOT NULL CHECK (BTRIM(reporter_name_snapshot) <> ''),
  category TEXT NOT NULL CHECK (category IN ('booking','messages','profile','payments','other')),
  description TEXT NOT NULL CHECK (CHAR_LENGTH(BTRIM(description)) BETWEEN 10 AND 2000),
  expected_behavior TEXT CHECK (expected_behavior IS NULL OR CHAR_LENGTH(expected_behavior) <= 1000),
  related_appointment_id BIGINT REFERENCES appointments(id) ON DELETE SET NULL,
  page_path TEXT CHECK (page_path IS NULL OR CHAR_LENGTH(page_path) <= 240),
  request_id TEXT CHECK (request_id IS NULL OR CHAR_LENGTH(request_id) <= 120),
  diagnostic_context JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(diagnostic_context) = 'object'),
  screenshot_mime_type TEXT CHECK (screenshot_mime_type IS NULL OR screenshot_mime_type IN ('image/jpeg','image/png','image/webp')),
  screenshot_bytes BYTEA,
  screenshot_sha256 TEXT CHECK (screenshot_sha256 IS NULL OR screenshot_sha256 ~ '^[0-9a-f]{64}$'),
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','investigating','fixed','closed')),
  resolution_note TEXT CHECK (resolution_note IS NULL OR CHAR_LENGTH(resolution_note) <= 1000),
  managed_by_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT problem_report_single_reporter CHECK (
    (reporter_type = 'staff' AND reporter_staff_admin_id IS NOT NULL AND reporter_crm_v2_client_id IS NULL)
    OR
    (reporter_type = 'client' AND reporter_staff_admin_id IS NULL AND reporter_crm_v2_client_id IS NOT NULL)
  ),
  CONSTRAINT problem_report_screenshot_complete CHECK (
    (screenshot_mime_type IS NULL AND screenshot_bytes IS NULL AND screenshot_sha256 IS NULL)
    OR
    (screenshot_mime_type IS NOT NULL AND screenshot_bytes IS NOT NULL AND screenshot_sha256 IS NOT NULL
      AND OCTET_LENGTH(screenshot_bytes) <= 1048576)
  )
);

CREATE INDEX IF NOT EXISTS idx_problem_reports_status_created
  ON problem_reports(status, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_problem_reports_staff_reporter
  ON problem_reports(reporter_staff_admin_id, created_at DESC)
  WHERE reporter_staff_admin_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_problem_reports_client_reporter
  ON problem_reports(reporter_crm_v2_client_id, created_at DESC)
  WHERE reporter_crm_v2_client_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS problem_report_whatsapp_intents (
  sender_hash TEXT PRIMARY KEY CHECK (sender_hash ~ '^[0-9a-f]{64}$'),
  reporter_type TEXT NOT NULL CHECK (reporter_type IN ('client','staff')),
  reporter_staff_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  reporter_crm_v2_client_id BIGINT REFERENCES crm_v2_clients(id) ON DELETE CASCADE,
  step TEXT NOT NULL CHECK (step IN ('category','description')),
  category TEXT CHECK (category IS NULL OR category IN ('booking','messages','profile','payments','other')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT problem_report_intent_single_reporter CHECK (
    (reporter_type = 'staff' AND reporter_staff_admin_id IS NOT NULL AND reporter_crm_v2_client_id IS NULL)
    OR
    (reporter_type = 'client' AND reporter_staff_admin_id IS NULL AND reporter_crm_v2_client_id IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_problem_report_whatsapp_intents_expiry
  ON problem_report_whatsapp_intents(expires_at);

DO $$
DECLARE
  target_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO target_count
    FROM staff_admin_accounts
   WHERE active = TRUE
     AND LOWER(BTRIM(display_name)) IN ('jean-pierre','jean pierre','jp')
     AND business_role = 'business_admin';

  IF target_count <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one active canonical Jean-Pierre business_admin; found %', target_count;
  END IF;

  UPDATE staff_admin_accounts
     SET permissions = COALESCE(permissions, '{}'::jsonb)
                       || '{"problem_reports:manage":true}'::jsonb,
         updated_at = NOW()
   WHERE active = TRUE
     AND LOWER(BTRIM(display_name)) IN ('jean-pierre','jean pierre','jp')
     AND business_role = 'business_admin';
END $$;

COMMENT ON TABLE problem_reports IS
  'Authenticated client and staff problem reports. Only the explicitly permissioned JP account may list or manage the private inbox.';
