-- Reporter-visible status history and durable resolution notifications.

ALTER TABLE problem_reports
  ADD COLUMN IF NOT EXISTS revision BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS problem_report_status_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  problem_report_id BIGINT NOT NULL REFERENCES problem_reports(id) ON DELETE RESTRICT,
  from_status TEXT NOT NULL CHECK (from_status IN ('new','investigating','fixed','closed')),
  to_status TEXT NOT NULL CHECK (to_status IN ('new','investigating','fixed','closed')),
  resolution_note_snapshot TEXT CHECK (resolution_note_snapshot IS NULL OR CHAR_LENGTH(resolution_note_snapshot) <= 1000),
  actor_admin_id BIGINT REFERENCES staff_admin_accounts(id) ON DELETE SET NULL,
  actor_kind TEXT NOT NULL CHECK (actor_kind IN ('staff','reporter','system')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_problem_report_status_events_report
  ON problem_report_status_events(problem_report_id, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS problem_report_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  problem_report_id BIGINT NOT NULL REFERENCES problem_reports(id) ON DELETE RESTRICT,
  event_type TEXT NOT NULL CHECK (event_type IN ('resolved')),
  report_revision BIGINT NOT NULL,
  state TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','sending','sent','failed')),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  claimed_at TIMESTAMPTZ,
  provider_message_id TEXT,
  error_code TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at TIMESTAMPTZ,
  UNIQUE(problem_report_id,event_type,report_revision)
);

CREATE INDEX IF NOT EXISTS idx_problem_report_notifications_due
  ON problem_report_notifications(next_attempt_at, id)
  WHERE state IN ('pending','failed');

COMMENT ON TABLE problem_report_notifications IS
  'Durable WhatsApp outbox for problem-report resolution updates; in-app status remains authoritative.';
