-- My Shiloh once-off welcome voucher.
-- This promotional value is deliberately separate from paid gift vouchers,
-- the 5% Shiloh Rewards wallet, and cash/provider payment evidence.

CREATE TABLE IF NOT EXISTS my_shiloh_welcome_voucher_settings (
  singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
  amount NUMERIC(12,2) NOT NULL DEFAULT 100.00 CHECK (amount > 0),
  minimum_booking_value NUMERIC(12,2) NOT NULL DEFAULT 450.00 CHECK (minimum_booking_value > 0),
  validity_days INTEGER NOT NULL DEFAULT 60 CHECK (validity_days BETWEEN 1 AND 365),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  activated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO my_shiloh_welcome_voucher_settings
  (singleton,amount,minimum_booking_value,validity_days,active)
VALUES(TRUE,100.00,450.00,60,TRUE)
ON CONFLICT(singleton) DO NOTHING;

CREATE TABLE IF NOT EXISTS my_shiloh_welcome_vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crm_v2_client_id BIGINT NOT NULL UNIQUE REFERENCES crm_v2_clients(id) ON DELETE RESTRICT,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  minimum_booking_value NUMERIC(12,2) NOT NULL CHECK (minimum_booking_value > 0),
  state TEXT NOT NULL DEFAULT 'available' CHECK (state IN ('available','redeemed','expired','cancelled')),
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  redeemed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT welcome_voucher_expiry_after_issue CHECK (expires_at > issued_at),
  CONSTRAINT welcome_voucher_redemption_state CHECK (
    (state = 'redeemed' AND redeemed_at IS NOT NULL) OR
    (state <> 'redeemed' AND redeemed_at IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_my_shiloh_welcome_vouchers_state_expiry
  ON my_shiloh_welcome_vouchers(state,expires_at);

CREATE TABLE IF NOT EXISTS booking_welcome_voucher_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  welcome_voucher_id BIGINT NOT NULL UNIQUE REFERENCES my_shiloh_welcome_vouchers(id) ON DELETE RESTRICT,
  booking_payment_account_id BIGINT NOT NULL REFERENCES booking_payment_accounts(id) ON DELETE RESTRICT,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  state TEXT NOT NULL DEFAULT 'applied' CHECK (state IN ('applied','reversed')),
  applied_by_client_session_id BIGINT NOT NULL REFERENCES client_browser_sessions(id) ON DELETE RESTRICT,
  operation_key TEXT NOT NULL UNIQUE,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reversed_at TIMESTAMPTZ,
  CONSTRAINT welcome_voucher_allocation_reversal CHECK (
    (state = 'applied' AND reversed_at IS NULL) OR
    (state = 'reversed' AND reversed_at IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_booking_welcome_voucher_allocations_account
  ON booking_welcome_voucher_allocations(booking_payment_account_id,state,applied_at DESC);

COMMENT ON TABLE my_shiloh_welcome_vouchers IS
  'One registration-completion welcome voucher per canonical verified My Shiloh client.';
COMMENT ON TABLE booking_welcome_voucher_allocations IS
  'Welcome voucher value applied to a qualifying booking, separate from cash, gift vouchers and Shiloh Rewards.';
