-- Register already-preprinted walk-in gift vouchers against Shiloh's canonical
-- voucher balance and audit authorities. No parallel voucher register is created.

ALTER TABLE gift_voucher_orders
  ALTER COLUMN purchaser_crm_v2_client_id DROP NOT NULL,
  ALTER COLUMN delivery_recipient DROP NOT NULL,
  ALTER COLUMN delivery_mobile DROP NOT NULL;

ALTER TABLE gift_voucher_orders
  ADD COLUMN IF NOT EXISTS order_source TEXT NOT NULL DEFAULT 'online'
    CHECK (order_source IN ('online','walk_in')),
  ADD COLUMN IF NOT EXISTS purchaser_name TEXT
    CHECK (purchaser_name IS NULL OR CHAR_LENGTH(TRIM(purchaser_name)) BETWEEN 1 AND 120),
  ADD COLUMN IF NOT EXISTS stock_reference TEXT
    CHECK (stock_reference IS NULL OR CHAR_LENGTH(TRIM(stock_reference)) <= 80),
  ADD COLUMN IF NOT EXISTS created_by_admin_id BIGINT
    REFERENCES staff_admin_accounts(id) ON DELETE SET NULL;

UPDATE gift_voucher_orders o
   SET purchaser_name = c.name
  FROM crm_v2_clients c
 WHERE o.purchaser_crm_v2_client_id = c.id
   AND o.purchaser_name IS NULL;

ALTER TABLE gift_voucher_orders
  DROP CONSTRAINT IF EXISTS gift_voucher_orders_source_contract;
ALTER TABLE gift_voucher_orders
  ADD CONSTRAINT gift_voucher_orders_source_contract CHECK (
    (
      order_source = 'online'
      AND purchaser_crm_v2_client_id IS NOT NULL
      AND delivery_recipient IS NOT NULL
      AND delivery_mobile IS NOT NULL
    )
    OR
    (
      order_source = 'walk_in'
      AND purchaser_name IS NOT NULL
      AND created_by_admin_id IS NOT NULL
      AND (
        (delivery_recipient IS NULL AND delivery_mobile IS NULL)
        OR
        (delivery_recipient = 'recipient' AND delivery_mobile IS NOT NULL)
      )
    )
  );

CREATE UNIQUE INDEX IF NOT EXISTS uq_gift_voucher_orders_stock_reference
  ON gift_voucher_orders(LOWER(stock_reference))
  WHERE stock_reference IS NOT NULL;

ALTER TABLE gift_vouchers
  ADD COLUMN IF NOT EXISTS access_key TEXT;

UPDATE gift_vouchers v
   SET access_key = pr.request_key
  FROM payment_requests pr
 WHERE pr.gift_voucher_order_id = v.order_id
   AND v.access_key IS NULL;

ALTER TABLE gift_vouchers
  ALTER COLUMN access_key SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_gift_vouchers_access_key
  ON gift_vouchers(access_key);

CREATE TABLE IF NOT EXISTS gift_voucher_payment_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL UNIQUE REFERENCES gift_voucher_orders(id) ON DELETE RESTRICT,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  currency CHAR(3) NOT NULL DEFAULT 'ZAR' CHECK (currency = 'ZAR'),
  method TEXT NOT NULL CHECK (method IN ('cash','card_machine','manual_eft')),
  evidence_kind TEXT NOT NULL DEFAULT 'authorized_manual'
    CHECK (evidence_kind = 'authorized_manual'),
  operation_key TEXT NOT NULL UNIQUE,
  external_reference TEXT
    CHECK (external_reference IS NULL OR CHAR_LENGTH(TRIM(external_reference)) <= 120),
  actor_admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gift_voucher_payment_entries_created
  ON gift_voucher_payment_entries(created_at DESC);

UPDATE staff_admin_accounts
   SET permissions = COALESCE(permissions, '{}'::jsonb) || '{"voucher:issue":true}'::jsonb,
       updated_at = NOW()
 WHERE active = TRUE
   AND business_role IN ('owner','booking_operator')
   AND calendar_scope = 'all_business'
   AND service_scope = 'all_services';

COMMENT ON TABLE gift_voucher_payment_entries IS
  'Immutable authorised in-person payment evidence for preprinted Shiloh gift vouchers.';
COMMENT ON COLUMN gift_voucher_orders.stock_reference IS
  'Optional reference already printed on or assigned to the physical voucher stock; it is not the redeemable voucher code.';
COMMENT ON COLUMN gift_vouchers.access_key IS
  'Private non-sequential key used only for the secure voucher view and optional WhatsApp delivery.';
