-- Shiloh booking deposit policy.
-- Payment truth remains separate from appointment/attendance truth.
-- This policy is prospective from the production migration timestamp.

CREATE TABLE IF NOT EXISTS booking_deposit_policies (
  policy_key TEXT PRIMARY KEY,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  deposit_basis_points INTEGER NOT NULL CHECK (deposit_basis_points BETWEEN 0 AND 10000),
  full_release_notice_hours INTEGER NOT NULL CHECK (full_release_notice_hours > 0),
  partial_notice_hours INTEGER NOT NULL CHECK (partial_notice_hours >= 0 AND partial_notice_hours < full_release_notice_hours),
  partial_retention_basis_points INTEGER NOT NULL CHECK (partial_retention_basis_points BETWEEN 0 AND 10000),
  late_retention_basis_points INTEGER NOT NULL CHECK (late_retention_basis_points BETWEEN 0 AND 10000),
  no_show_retention_basis_points INTEGER NOT NULL CHECK (no_show_retention_basis_points BETWEEN 0 AND 10000),
  exempt_staff_display_name TEXT NOT NULL CHECK (BTRIM(exempt_staff_display_name) <> ''),
  exempt_staff_business_role TEXT NOT NULL CHECK (BTRIM(exempt_staff_business_role) <> ''),
  activated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO booking_deposit_policies(
  policy_key,active,deposit_basis_points,full_release_notice_hours,partial_notice_hours,
  partial_retention_basis_points,late_retention_basis_points,no_show_retention_basis_points,
  exempt_staff_display_name,exempt_staff_business_role
) VALUES(
  'shiloh_booking_deposit_v1',TRUE,5000,48,24,5000,10000,10000,'Marietjie','tenant_practitioner'
)
ON CONFLICT (policy_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS booking_payment_requirements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_account_id BIGINT NOT NULL UNIQUE REFERENCES booking_payment_accounts(id) ON DELETE RESTRICT,
  requirement_type TEXT NOT NULL DEFAULT 'booking_deposit' CHECK (requirement_type='booking_deposit'),
  policy_key TEXT NOT NULL REFERENCES booking_deposit_policies(policy_key) ON DELETE RESTRICT,
  percentage_basis_points INTEGER NOT NULL CHECK (percentage_basis_points BETWEEN 0 AND 10000),
  eligible_amount_base NUMERIC(12,2) NOT NULL CHECK (eligible_amount_base >= 0),
  required_amount NUMERIC(12,2) NOT NULL CHECK (required_amount >= 0),
  full_release_notice_hours INTEGER NOT NULL CHECK (full_release_notice_hours > 0),
  partial_notice_hours INTEGER NOT NULL CHECK (partial_notice_hours >= 0),
  partial_retention_basis_points INTEGER NOT NULL CHECK (partial_retention_basis_points BETWEEN 0 AND 10000),
  late_retention_basis_points INTEGER NOT NULL CHECK (late_retention_basis_points BETWEEN 0 AND 10000),
  no_show_retention_basis_points INTEGER NOT NULL CHECK (no_show_retention_basis_points BETWEEN 0 AND 10000),
  exempt_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS booking_payment_requirement_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requirement_id BIGINT NOT NULL REFERENCES booking_payment_requirements(id) ON DELETE RESTRICT,
  appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE RESTRICT,
  eligible_amount NUMERIC(12,2) NOT NULL CHECK (eligible_amount >= 0),
  required_amount NUMERIC(12,2) NOT NULL CHECK (required_amount >= 0),
  exempt_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(requirement_id,appointment_id)
);

ALTER TABLE payment_requests
  ADD COLUMN IF NOT EXISTS purpose TEXT NOT NULL DEFAULT 'balance',
  ADD COLUMN IF NOT EXISTS deposit_appointment_id BIGINT REFERENCES appointments(id) ON DELETE SET NULL;

ALTER TABLE payment_requests
  DROP CONSTRAINT IF EXISTS payment_requests_purpose_check;

ALTER TABLE payment_requests
  ADD CONSTRAINT payment_requests_purpose_check
    CHECK (purpose IN ('balance','deposit','split','voucher'));

CREATE INDEX IF NOT EXISTS idx_payment_requests_deposit_subject
  ON payment_requests(payment_account_id,deposit_appointment_id,created_at DESC)
  WHERE purpose='deposit';

CREATE TABLE IF NOT EXISTS booking_deposit_dispositions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requirement_id BIGINT NOT NULL REFERENCES booking_payment_requirements(id) ON DELETE RESTRICT,
  appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE RESTRICT,
  event_kind TEXT NOT NULL CHECK (event_kind IN ('rescheduled','cancelled','no_show')),
  event_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  original_starts_at TIMESTAMPTZ NOT NULL,
  notice_hours NUMERIC(12,2),
  retention_basis_points INTEGER NOT NULL CHECK (retention_basis_points BETWEEN 0 AND 10000),
  appointment_deposit_share NUMERIC(12,2) NOT NULL CHECK (appointment_deposit_share >= 0),
  policy_retention_amount NUMERIC(12,2) NOT NULL CHECK (policy_retention_amount >= 0),
  retained_amount NUMERIC(12,2) NOT NULL CHECK (retained_amount >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_booking_deposit_dispositions_requirement
  ON booking_deposit_dispositions(requirement_id,created_at);

ALTER TABLE customer_message_deliveries
  DROP CONSTRAINT IF EXISTS customer_message_deliveries_status_check;

ALTER TABLE customer_message_deliveries
  ADD CONSTRAINT customer_message_deliveries_status_check
    CHECK (status IN ('pending','awaiting_payment','sending','sent','failed','uncertain'));

CREATE OR REPLACE FUNCTION record_booking_deposit_policy_disposition()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  requirement_row booking_payment_requirements%ROWTYPE;
  item_row booking_payment_requirement_items%ROWTYPE;
  account_id BIGINT;
  event_name TEXT;
  event_time TIMESTAMPTZ := clock_timestamp();
  hours_notice NUMERIC(12,2);
  retention_bps INTEGER;
  retention_cap NUMERIC(12,2);
  net_received NUMERIC(12,2);
  already_retained NUMERIC(12,2);
  available_to_retain NUMERIC(12,2);
  actual_retained NUMERIC(12,2);
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status AND NEW.status='no_show' THEN
    event_name := 'no_show';
  ELSIF NEW.status IS DISTINCT FROM OLD.status AND NEW.status='cancelled' THEN
    event_name := 'cancelled';
  ELSIF NEW.starts_at IS DISTINCT FROM OLD.starts_at THEN
    event_name := 'rescheduled';
  ELSE
    RETURN NEW;
  END IF;

  SELECT req, item
    INTO requirement_row, item_row
    FROM booking_payment_requirement_items item
    JOIN booking_payment_requirements req ON req.id=item.requirement_id
   WHERE item.appointment_id=NEW.id
   ORDER BY req.id DESC
   LIMIT 1;

  IF NOT FOUND OR item_row.required_amount <= 0 THEN
    RETURN NEW;
  END IF;

  SELECT req.payment_account_id
    INTO account_id
    FROM booking_payment_requirements req
   WHERE req.id=requirement_row.id;

  hours_notice := ROUND((EXTRACT(EPOCH FROM (OLD.starts_at-event_time))/3600.0)::numeric,2);

  IF event_name='no_show' THEN
    retention_bps := requirement_row.no_show_retention_basis_points;
  ELSIF hours_notice >= requirement_row.full_release_notice_hours THEN
    retention_bps := 0;
  ELSIF hours_notice >= requirement_row.partial_notice_hours THEN
    retention_bps := requirement_row.partial_retention_basis_points;
  ELSE
    retention_bps := requirement_row.late_retention_basis_points;
  END IF;

  retention_cap := ROUND(item_row.required_amount * retention_bps / 10000.0,2);

  SELECT COALESCE(SUM(CASE WHEN entry_type='payment' THEN amount ELSE -amount END),0)
    INTO net_received
    FROM payment_ledger_entries
   WHERE payment_account_id=account_id;

  SELECT COALESCE(SUM(retained_amount),0)
    INTO already_retained
    FROM booking_deposit_dispositions
   WHERE requirement_id=requirement_row.id;

  available_to_retain := GREATEST(0,net_received-already_retained);
  actual_retained := LEAST(retention_cap,available_to_retain);

  INSERT INTO booking_deposit_dispositions(
    requirement_id,appointment_id,event_kind,event_at,original_starts_at,notice_hours,
    retention_basis_points,appointment_deposit_share,policy_retention_amount,retained_amount
  ) VALUES(
    requirement_row.id,NEW.id,event_name,event_time,OLD.starts_at,hours_notice,
    retention_bps,item_row.required_amount,retention_cap,actual_retained
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_booking_deposit_policy_disposition ON appointments;
CREATE TRIGGER trg_booking_deposit_policy_disposition
AFTER UPDATE OF starts_at,status ON appointments
FOR EACH ROW
WHEN (
  OLD.starts_at IS DISTINCT FROM NEW.starts_at
  OR (OLD.status IS DISTINCT FROM NEW.status AND NEW.status IN ('cancelled','no_show'))
)
EXECUTE FUNCTION record_booking_deposit_policy_disposition();

COMMENT ON TABLE booking_payment_requirements IS
  'Prospective booking-deposit obligations. Payment evidence remains in the immutable payment ledger.';
COMMENT ON TABLE booking_deposit_dispositions IS
  'Policy calculations for reschedule/cancellation/no-show. These rows never issue a refund or mutate payment evidence.';
