-- Shiloh clinic-wide booking deposit policy.
-- Payment truth remains in booking_payment_accounts/payment_ledger_entries.
-- This layer records what deposit is required and the agreed cancellation/no-show consequence.

CREATE TABLE IF NOT EXISTS clinic_booking_deposit_policy (
  id SMALLINT PRIMARY KEY CHECK (id = 1),
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  rate_basis_points INTEGER NOT NULL CHECK (rate_basis_points BETWEEN 1 AND 10000),
  free_notice_hours INTEGER NOT NULL CHECK (free_notice_hours > 0),
  partial_notice_hours INTEGER NOT NULL CHECK (partial_notice_hours > 0),
  partial_forfeit_basis_points INTEGER NOT NULL CHECK (partial_forfeit_basis_points BETWEEN 0 AND 10000),
  late_forfeit_basis_points INTEGER NOT NULL CHECK (late_forfeit_basis_points BETWEEN 0 AND 10000),
  no_show_forfeit_basis_points INTEGER NOT NULL CHECK (no_show_forfeit_basis_points BETWEEN 0 AND 10000),
  exempt_staff_id BIGINT NOT NULL REFERENCES staff(id) ON DELETE RESTRICT,
  effective_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  policy_version TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (partial_notice_hours < free_notice_hours)
);

DO $$
DECLARE
  marietjie_id BIGINT;
  matched INTEGER;
BEGIN
  SELECT COUNT(*), MIN(id)
    INTO matched, marietjie_id
    FROM staff
   WHERE status='active'
     AND LOWER(TRIM(display_name))='marietjie';

  IF matched <> 1 THEN
    RAISE EXCEPTION 'Deposit policy requires exactly one active Marietjie staff record; found %', matched;
  END IF;

  INSERT INTO clinic_booking_deposit_policy(
    id, enabled, rate_basis_points, free_notice_hours, partial_notice_hours,
    partial_forfeit_basis_points, late_forfeit_basis_points, no_show_forfeit_basis_points,
    exempt_staff_id, policy_version
  )
  VALUES(1, TRUE, 5000, 48, 24, 5000, 10000, 10000, marietjie_id, '2026-09-23-v1')
  ON CONFLICT (id) DO NOTHING;
END $$;

CREATE TABLE IF NOT EXISTS booking_deposit_requirements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_account_id BIGINT NOT NULL UNIQUE REFERENCES booking_payment_accounts(id) ON DELETE RESTRICT,
  policy_id SMALLINT NOT NULL REFERENCES clinic_booking_deposit_policy(id) ON DELETE RESTRICT,
  policy_version TEXT NOT NULL,
  rate_basis_points INTEGER NOT NULL CHECK (rate_basis_points BETWEEN 1 AND 10000),
  eligible_amount NUMERIC(12,2) NOT NULL CHECK (eligible_amount >= 0),
  required_amount NUMERIC(12,2) NOT NULL CHECK (required_amount >= 0),
  state TEXT NOT NULL CHECK (state IN ('awaiting','satisfied','exempt')),
  satisfied_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ((state='exempt' AND required_amount=0) OR state<>'exempt')
);

CREATE TABLE IF NOT EXISTS booking_deposit_requirement_members (
  requirement_id BIGINT NOT NULL REFERENCES booking_deposit_requirements(id) ON DELETE RESTRICT,
  appointment_id BIGINT NOT NULL UNIQUE REFERENCES appointments(id) ON DELETE RESTRICT,
  eligible_amount NUMERIC(12,2) NOT NULL CHECK (eligible_amount >= 0),
  required_amount NUMERIC(12,2) NOT NULL CHECK (required_amount >= 0),
  exemption_reason TEXT,
  PRIMARY KEY(requirement_id, appointment_id),
  CHECK ((required_amount=0 AND exemption_reason IS NOT NULL) OR required_amount>0)
);

ALTER TABLE payment_requests
  ADD COLUMN IF NOT EXISTS purpose TEXT NOT NULL DEFAULT 'general',
  ADD COLUMN IF NOT EXISTS deposit_requirement_id BIGINT REFERENCES booking_deposit_requirements(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS deposit_member_appointment_id BIGINT REFERENCES appointments(id) ON DELETE RESTRICT;

ALTER TABLE payment_requests DROP CONSTRAINT IF EXISTS payment_requests_purpose_check;
ALTER TABLE payment_requests ADD CONSTRAINT payment_requests_purpose_check
  CHECK (purpose IN ('general','deposit','balance','split','voucher'));

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_requests_deposit_member
  ON payment_requests(deposit_requirement_id, deposit_member_appointment_id)
  WHERE purpose='deposit' AND deposit_requirement_id IS NOT NULL AND deposit_member_appointment_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_booking_deposit_requirements_state
  ON booking_deposit_requirements(state, created_at DESC);

CREATE TABLE IF NOT EXISTS booking_deposit_policy_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_status_history_id BIGINT NOT NULL UNIQUE REFERENCES appointment_status_history(id) ON DELETE RESTRICT,
  requirement_id BIGINT NOT NULL REFERENCES booking_deposit_requirements(id) ON DELETE RESTRICT,
  appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE RESTRICT,
  event_type TEXT NOT NULL CHECK (event_type IN ('cancelled','no_show')),
  notice_minutes INTEGER,
  forfeit_basis_points INTEGER NOT NULL CHECK (forfeit_basis_points BETWEEN 0 AND 10000),
  member_required_amount NUMERIC(12,2) NOT NULL CHECK (member_required_amount >= 0),
  policy_forfeit_amount NUMERIC(12,2) NOT NULL CHECK (policy_forfeit_amount >= 0),
  policy_creditable_amount NUMERIC(12,2) NOT NULL CHECK (policy_creditable_amount >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION record_booking_deposit_policy_event()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  req booking_deposit_requirements%ROWTYPE;
  member booking_deposit_requirement_members%ROWTYPE;
  policy clinic_booking_deposit_policy%ROWTYPE;
  start_at TIMESTAMPTZ;
  notice_mins INTEGER;
  forfeit_bps INTEGER;
  forfeit_amount NUMERIC(12,2);
BEGIN
  IF NEW.to_status NOT IN ('cancelled','no_show') THEN
    RETURN NEW;
  END IF;

  SELECT m.* INTO member
    FROM booking_deposit_requirement_members m
   WHERE m.appointment_id=NEW.appointment_id;
  IF NOT FOUND OR member.required_amount <= 0 THEN
    RETURN NEW;
  END IF;

  SELECT * INTO req FROM booking_deposit_requirements WHERE id=member.requirement_id;
  SELECT * INTO policy FROM clinic_booking_deposit_policy WHERE id=req.policy_id;
  SELECT starts_at INTO start_at FROM appointments WHERE id=NEW.appointment_id;

  notice_mins := FLOOR(EXTRACT(EPOCH FROM (start_at - NEW.changed_at)) / 60);

  IF NEW.to_status='no_show' THEN
    forfeit_bps := policy.no_show_forfeit_basis_points;
  ELSIF notice_mins >= policy.free_notice_hours * 60 THEN
    forfeit_bps := 0;
  ELSIF notice_mins >= policy.partial_notice_hours * 60 THEN
    forfeit_bps := policy.partial_forfeit_basis_points;
  ELSE
    forfeit_bps := policy.late_forfeit_basis_points;
  END IF;

  forfeit_amount := ROUND(member.required_amount * forfeit_bps / 10000.0, 2);

  INSERT INTO booking_deposit_policy_events(
    appointment_status_history_id, requirement_id, appointment_id, event_type,
    notice_minutes, forfeit_basis_points, member_required_amount,
    policy_forfeit_amount, policy_creditable_amount
  )
  VALUES(
    NEW.id, req.id, NEW.appointment_id, NEW.to_status,
    notice_mins, forfeit_bps, member.required_amount,
    forfeit_amount, member.required_amount - forfeit_amount
  )
  ON CONFLICT (appointment_status_history_id) DO NOTHING;

  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_booking_deposit_policy_event ON appointment_status_history;
CREATE TRIGGER trg_booking_deposit_policy_event
AFTER INSERT ON appointment_status_history
FOR EACH ROW
EXECUTE FUNCTION record_booking_deposit_policy_event();

COMMENT ON TABLE clinic_booking_deposit_policy IS
  'Single Shiloh clinic booking-deposit authority. V1: 50%, 48/24-hour cancellation bands, Marietjie exempt.';
COMMENT ON TABLE booking_deposit_requirements IS
  'Required booking deposit only. Settlement truth remains in the canonical payment ledger.';
COMMENT ON TABLE booking_deposit_policy_events IS
  'Policy consequence evidence only. It never moves/refunds money automatically.';
