-- Additive client passkey enrollment and sign-in using existing client sessions.
-- This stores public WebAuthn keys only, never device biometrics or private keys.
CREATE TABLE client_auth_passkey_credentials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crm_v2_client_id BIGINT NOT NULL REFERENCES crm_v2_clients(id) ON DELETE RESTRICT,
  credential_id TEXT NOT NULL UNIQUE,
  public_key_spki BYTEA NOT NULL,
  algorithm INTEGER NOT NULL,
  sign_count BIGINT NOT NULL DEFAULT 0,
  transports JSONB NOT NULL DEFAULT '[]'::jsonb,
  backed_up BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  CONSTRAINT client_passkey_credential_id CHECK (credential_id ~ '^[A-Za-z0-9_-]{16,1024}$'),
  CONSTRAINT client_passkey_algorithm CHECK (algorithm IN (-7, -8, -257)),
  CONSTRAINT client_passkey_sign_count CHECK (sign_count >= 0),
  CONSTRAINT client_passkey_transports CHECK (jsonb_typeof(transports) = 'array')
);

CREATE INDEX idx_client_auth_passkeys_client_active
  ON client_auth_passkey_credentials(crm_v2_client_id, created_at DESC)
  WHERE revoked_at IS NULL;

CREATE TABLE client_auth_passkey_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_hash TEXT NOT NULL UNIQUE,
  crm_v2_client_id BIGINT NOT NULL REFERENCES crm_v2_clients(id) ON DELETE RESTRICT,
  session_id BIGINT NOT NULL REFERENCES client_browser_sessions(id) ON DELETE CASCADE,
  request_fingerprint_hash TEXT,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT client_passkey_challenge_hash CHECK (challenge_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT client_passkey_challenge_expiry CHECK (expires_at > created_at)
);

CREATE INDEX idx_client_auth_passkey_challenges_session
  ON client_auth_passkey_challenges(session_id, expires_at DESC)
  WHERE consumed_at IS NULL;

-- Guest sign-in challenges are separate from enrollment and are bound to an
-- HttpOnly browser token. They reveal no client identity until key verification.
CREATE TABLE client_auth_passkey_login_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_hash TEXT NOT NULL UNIQUE,
  browser_token_hash TEXT NOT NULL UNIQUE,
  request_fingerprint_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT client_passkey_login_challenge_hash CHECK (challenge_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT client_passkey_login_browser_hash CHECK (browser_token_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT client_passkey_login_fingerprint CHECK (request_fingerprint_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT client_passkey_login_expiry CHECK (expires_at > created_at)
);

CREATE INDEX idx_client_auth_passkey_login_rate
  ON client_auth_passkey_login_challenges(request_fingerprint_hash, created_at DESC);
