-- One-time, client-owned recovery codes. Only hashes are retained.
CREATE TABLE client_auth_passkey_recovery_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crm_v2_client_id BIGINT NOT NULL REFERENCES crm_v2_clients(id) ON DELETE RESTRICT,
  code_hash TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  consumed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  CONSTRAINT client_passkey_recovery_hash CHECK (code_hash ~ '^[0-9a-f]{64}$')
);
CREATE UNIQUE INDEX client_passkey_recovery_one_active
  ON client_auth_passkey_recovery_codes(crm_v2_client_id)
  WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE TABLE client_auth_passkey_recovery_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_fingerprint_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT client_passkey_recovery_fingerprint CHECK (request_fingerprint_hash ~ '^[0-9a-f]{64}$')
);
CREATE INDEX client_passkey_recovery_attempt_rate
  ON client_auth_passkey_recovery_attempts(request_fingerprint_hash, created_at DESC);
