-- Staff device setup requires a recent passkey-authenticated administrator and
-- an SMS delivered to the staff account's recorded number. Store no plaintext code.
CREATE TABLE staff_auth_sms_device_setups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id) ON DELETE CASCADE,
  operator_admin_id BIGINT NOT NULL REFERENCES staff_admin_accounts(id),
  request_hash TEXT NOT NULL UNIQUE CHECK (request_hash ~ '^[0-9a-f]{64}$'),
  code_hash TEXT NOT NULL CHECK (code_hash ~ '^[0-9a-f]{64}$'),
  mobile_hash TEXT NOT NULL CHECK (mobile_hash ~ '^[0-9a-f]{64}$'),
  mode TEXT NOT NULL CHECK (mode IN ('add', 'replace')),
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL CHECK (expires_at > issued_at),
  verify_attempts INTEGER NOT NULL DEFAULT 0,
  provider_message_id TEXT,
  consumed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ
);
CREATE INDEX idx_staff_auth_sms_device_setups_admin_issued
  ON staff_auth_sms_device_setups(admin_id, issued_at DESC);

ALTER TABLE staff_auth_passkey_bootstraps
  DROP CONSTRAINT IF EXISTS staff_auth_passkey_bootstrap_source_check;
ALTER TABLE staff_auth_passkey_bootstraps
  ADD CONSTRAINT staff_auth_passkey_bootstrap_source_check
    CHECK (source IN ('whatsapp_self', 'workspace_self', 'admin_sms_add', 'admin_sms_replace'));
