-- Synthetic dependency tables. CRM and linked-group constraints use production migrations.
CREATE TABLE locations(id BIGINT PRIMARY KEY,status TEXT NOT NULL);
CREATE TABLE services(id BIGINT PRIMARY KEY,name TEXT,price NUMERIC(12,2),duration_minutes INT,processing_time_minutes INT DEFAULT 0,extra_time_minutes INT DEFAULT 0,status TEXT,variable_price BOOLEAN DEFAULT FALSE,external_source TEXT);
CREATE TABLE staff(id BIGINT PRIMARY KEY,display_name TEXT,status TEXT,resource_type TEXT,client_bookable BOOLEAN,business_role TEXT);
CREATE TABLE staff_services(staff_id BIGINT REFERENCES staff(id),service_id BIGINT REFERENCES services(id),PRIMARY KEY(staff_id,service_id));
CREATE TABLE service_packages(session_service_id BIGINT,status TEXT);
CREATE TABLE staff_admin_accounts(id BIGINT PRIMARY KEY,permissions JSONB,updated_at TIMESTAMPTZ,active BOOLEAN,business_role TEXT,calendar_scope TEXT,service_scope TEXT);
CREATE TABLE appointments(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,client_id BIGINT,source_client_name TEXT,location_id BIGINT REFERENCES locations(id),starts_at TIMESTAMPTZ NOT NULL,ends_at TIMESTAMPTZ NOT NULL,status TEXT,title TEXT,total_price NUMERIC(12,2),currency TEXT,source TEXT,CHECK(ends_at>starts_at));
CREATE TABLE appointment_services(appointment_id BIGINT REFERENCES appointments(id),service_id BIGINT REFERENCES services(id),position INT,service_name_snapshot TEXT,price_snapshot NUMERIC(12,2),duration_minutes_snapshot INT);
CREATE TABLE appointment_staff(appointment_id BIGINT REFERENCES appointments(id),staff_id BIGINT REFERENCES staff(id),position INT,staff_name_snapshot TEXT);
CREATE TABLE booking_policy_acceptances(phone TEXT,policy_version TEXT,channel TEXT,accepted_at TIMESTAMPTZ,appointment_id BIGINT REFERENCES appointments(id),crm_v2_client_id BIGINT);
CREATE TABLE appointment_booking_approvals(appointment_id BIGINT UNIQUE REFERENCES appointments(id),status TEXT);
CREATE TABLE appointment_status_history(appointment_id BIGINT REFERENCES appointments(id),from_status TEXT,to_status TEXT,changed_by TEXT,reason TEXT);
CREATE TABLE crm_audit_events(action TEXT,entity_type TEXT,entity_id BIGINT,metadata JSONB);
